import "./emoji.js?v=20260805-emoji-images-1";

const $=selector=>document.querySelector(selector);
const sortWords=shuffle([
  {word:"ก้ม",emoji:"🙇",target:true},{word:"จิ้ม",emoji:"👉",target:true},{word:"ตอม",emoji:"🪰",target:true},{word:"ทีม",emoji:"👥",target:true},{word:"ยอม",emoji:"🤝",target:true},
  {word:"ส้วม",emoji:"🚽",target:true},{word:"เอี่ยม",emoji:"✨",target:true},{word:"ประชุม",emoji:"🗣️",target:true},{word:"สนาม",emoji:"🏟️",target:true},{word:"กลุ่ม",emoji:"👨‍👩‍👧‍👦",target:true},
  {word:"กบ",emoji:"🐸",target:false},{word:"จาน",emoji:"🍽️",target:false},{word:"รถ",emoji:"🚗",target:false},{word:"ผัก",emoji:"🥬",target:false},{word:"ถ้วย",emoji:"🥣",target:false},
  {word:"ภาพ",emoji:"🖼️",target:false},{word:"นิ้ว",emoji:"☝️",target:false},{word:"ปลาวาฬ",emoji:"🐋",target:false},{word:"สนุก",emoji:"🎉",target:false},{word:"ทุ่ง",emoji:"🌾",target:false},
]);
const pictureWords=shuffle([
  {emoji:"🥗",words:["แม่","ทำ","ส้มตำ"],target:"ส้มตำ"},{emoji:"🍚",words:["น้อง","กิน","ข้าวต้ม"],target:"ข้าวต้ม"},
  {emoji:"☂️",words:["พี่","กาง","ร่ม"],target:"ร่ม"},{emoji:"👵",words:["ยาย","อุ้ม","หลาน"],target:"อุ้ม"},
  {emoji:"🕷️",words:["แมงมุม","ชัก","ใย"],target:"แมงมุม"},{emoji:"🌀",words:["พ่อ","เปิด","พัดลม"],target:"พัดลม"},
  {emoji:"🛑",words:["ครู","ห้าม","วิ่ง"],target:"ห้าม"},{emoji:"🏃",words:["เด็ก","เล่น","ใน","สนาม"],target:"สนาม"},
  {emoji:"🛏️",words:["แม่","ซื้อ","ผ้านวม","ใหม่"],target:"ผ้านวม"},{emoji:"🕳️",words:["ตา","ขุด","หลุม","ลึก"],target:"หลุม"},
]);
const exitQuestions=shuffle([
  {q:"คำมาตราแม่กมมีลักษณะอย่างไร",choices:["มี ม เป็นตัวสะกด","ไม่มีตัวสะกด","มี ง เป็นตัวสะกด"],answer:"มี ม เป็นตัวสะกด"},
  {q:"คำใดอยู่ในมาตราแม่กม",choices:["ยืม","ธง","นก"],answer:"ยืม"},
  {q:"คำใดไม่ใช่คำมาตราแม่กม",choices:["ร่ม","ส้ม","ทุ่ง"],answer:"ทุ่ง"},
  {q:"ข้อใดเป็นคำมาตราแม่กมทั้ง 2 คำ",choices:["ชม, ห้าม","ธง, สนาม","นก, ลม"],answer:"ชม, ห้าม"},
  {q:"ตัวสะกดของคำว่า “สนาม” คือข้อใด",choices:["ม","น","ง"],answer:"ม"},
]);
const missions=[{title:"กล่องคำแม่กม",total:sortWords.length},{title:"ภาพนี้คำอะไร",total:pictureWords.length},{title:"แบบทดสอบท้ายคาบ",total:exitQuestions.length}];
const lessonTitles=["เข้าห้องเรียน","เพลงแม่กม","สำรวจคำศัพท์","สรุปหลักแม่กม","สาธิตเกม","เริ่ม 2 ภารกิจ","กระดานคะแนน","แผนผังกล่องคำ","สรุปและแบบทดสอบท้ายคาบ","มอบรางวัลและใบงาน"];
const state={mission:0,index:0,score:0,answers:[],busy:false,roundTimer:null,slide:0,classTimer:null,classSeconds:900,songTimer:null,selected:[],firstTry:true};
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function speak(text){if(!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="th-TH";u.rate=.75;window.speechSynthesis.speak(u)}
function toast(message){const e=$("#toast");e.textContent=message;e.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove("show"),1700)}
function stopTransient(){clearInterval(state.roundTimer);clearInterval(state.classTimer);clearInterval(state.songTimer);if("speechSynthesis"in window)window.speechSynthesis.cancel()}
function addScore(points){state.score+=points;$("#score").textContent=state.score}
function updateHeader(){const meta=missions[state.mission];$("#missionLabel").textContent=`ภารกิจ ${state.mission+1} จาก 3`;$("#missionTitle").textContent=meta.title;$("#roundLabel").textContent=`ข้อ ${Math.min(state.index+1,meta.total)} / ${meta.total}`;$("#progressBar").style.width=`${state.index/meta.total*100}%`}
function next(){clearInterval(state.roundTimer);state.index++;if(state.index>=missions[state.mission].total){state.mission++;state.index=0;if(state.mission>=3)return renderResult();addScore(5);toast("ผ่านภารกิจ! รับดาวโบนัส ⭐")}render()}
function render(){state.busy=false;updateHeader();if(state.mission===0)renderSort();if(state.mission===1)renderPicture();if(state.mission===2)renderExit()}
function resolveSort(item,answer,source){if(state.busy)return;state.busy=true;clearInterval(state.roundTimer);const correct=answer===item.target;source?.classList.add(correct?"correct":"wrong");state.answers.push({mission:"sort",correct,word:item.word});if(correct){addScore(10);toast("ถูกต้อง! กล่องเรืองแสง ✨");speak("เก่งมาก")}else toast(item.target?`${item.word} มี ม เป็นตัวสะกด`:`${item.word} ไม่ใช่คำแม่กม`);setTimeout(next,1100)}
function renderSort(){
  const item=sortWords[state.index];$("#stage").innerHTML=`<p class="instruction">ลากเฉพาะคำแม่กมลงกล่องให้ทันเวลา</p><div id="roundClock" class="round-clock">⏱️ 10 วินาที</div><div class="conveyor"><article id="movingWord" class="word-card" draggable="true"><span class="picture">${item.emoji}</span><strong>${item.word}</strong><br><button class="speak-button">🔊 ฟังคำ</button></article></div><div id="targetBox" class="drop-box">📦 กล่องคำแม่กม<br><small>คำที่มี ม เป็นตัวสะกด</small></div><div class="button-row"><button id="putWord" class="primary-button">ใส่กล่องแม่กม</button><button id="skipWord" class="secondary-button">ส่งคำนี้ต่อ</button></div>`;
  const card=$("#movingWord"),box=$("#targetBox");$(".speak-button").onclick=e=>{e.stopPropagation();speak(item.word)};card.ondragstart=e=>e.dataTransfer.setData("text/plain",item.word);box.ondragover=e=>{e.preventDefault();box.classList.add("drag-over")};box.ondragleave=()=>box.classList.remove("drag-over");box.ondrop=e=>{e.preventDefault();resolveSort(item,true,box)};$("#putWord").onclick=()=>resolveSort(item,true,$("#putWord"));$("#skipWord").onclick=()=>resolveSort(item,false,$("#skipWord"));
  let time=10;state.roundTimer=setInterval(()=>{time--;$("#roundClock").textContent=`⏱️ ${time} วินาที`;if(time<=0)resolveSort(item,false)},1000);
}
function renderPicture(){
  const item=pictureWords[state.index],bank=shuffle(item.words.map((word,index)=>({word,id:`${state.index}-${index}`})));state.selected=[];state.firstTry=true;
  $("#stage").innerHTML=`<p class="instruction">ดูภาพ แล้วแตะหรือลากคำตามลำดับเพื่อเรียงเป็นประโยค</p><div id="roundClock" class="round-clock">⏱️ 60 วินาที</div>
    <div class="rocket-scene"><span class="picture" style="font-size:90px">${item.emoji}</span><div id="sentenceOutput" class="sentence-output">แตะคำเพื่อเรียงประโยค</div></div>
    <div class="word-bank">${bank.map(x=>`<button class="word-button" draggable="true" data-id="${x.id}" data-word="${x.word}">${x.word}</button>`).join("")}</div>
    <p id="pictureFeedback" class="instruction" style="margin-top:12px">คำแม่กมจะแสดงเป็นสีพิเศษเมื่อตอบถูก</p>
    <div class="button-row"><button id="resetPicture" class="secondary-button">เริ่มเรียงใหม่</button><button id="checkPicture" class="primary-button">ตรวจคำตอบ</button></div>`;
  const output=$("#sentenceOutput"),paint=(showTarget=false)=>{output.innerHTML=state.selected.length?state.selected.map(x=>`<span class="${showTarget&&x.word===item.target?"is-target-word":""}">${x.word}</span>`).join(""):"แตะคำเพื่อเรียงประโยค"};
  const choose=button=>{if(!button||button.disabled)return;button.disabled=true;state.selected.push({word:button.dataset.word,id:button.dataset.id});paint()};
  const reset=()=>{state.selected=[];document.querySelectorAll("[data-id]").forEach(button=>button.disabled=false);output.style.borderColor="";paint()};
  document.querySelectorAll("[data-id]").forEach(button=>{button.onclick=()=>choose(button);button.ondragstart=e=>e.dataTransfer.setData("text/plain",button.dataset.id)});
  output.ondragover=e=>e.preventDefault();output.ondrop=e=>{e.preventDefault();choose(document.querySelector(`[data-id="${CSS.escape(e.dataTransfer.getData("text/plain"))}"]`))};
  $("#resetPicture").onclick=reset;$("#checkPicture").onclick=()=>checkPicture(item,false,paint,reset);
  let time=60;state.roundTimer=setInterval(()=>{time--;$("#roundClock").textContent=`⏱️ ${time} วินาที`;if(time<=0)checkPicture(item,true,paint,reset)},1000);
}
function checkPicture(item,timedOut,paint,reset){if(state.busy)return;const answer=item.words.join(" "),response=state.selected.map(x=>x.word).join(" ");if(!timedOut&&state.selected.length!==item.words.length){toast("เลือกคำให้ครบทุกคำก่อนนะ");return}if(!timedOut&&response!==answer){state.firstTry=false;$("#sentenceOutput").style.borderColor="#e45454";toast("ลำดับยังไม่ถูก ลองใหม่อีกครั้ง");navigator.vibrate?.([90,55,90]);setTimeout(reset,700);return}state.busy=true;clearInterval(state.roundTimer);const correct=!timedOut&&response===answer;if(correct&&state.firstTry)addScore(20);state.answers.push({mission:"picture",sentence:answer,correct:correct&&state.firstTry});if(correct){paint(true);$("#sentenceOutput").style.borderColor="#16a36a";$("#pictureFeedback").textContent=`ถูกต้อง! “${item.target}” เป็นคำแม่กม`;toast("เรียงประโยคถูกต้อง! 🏅");speak(answer)}else toast(`หมดเวลา ประโยคที่ถูกต้องคือ ${answer}`);setTimeout(next,1400)}
function renderExit(){const item=exitQuestions[state.index];$("#stage").innerHTML=`<article class="exit-question"><span class="eyebrow">แบบทดสอบท้ายคาบ ข้อที่ ${state.index+1}</span><h2>${item.q}</h2><div class="exit-options">${shuffle(item.choices).map(c=>`<button data-choice="${c}">${c}</button>`).join("")}</div></article>`;document.querySelectorAll("[data-choice]").forEach(button=>button.onclick=()=>{if(state.busy)return;state.busy=true;const correct=button.dataset.choice===item.answer;button.classList.add(correct?"correct":"wrong");state.answers.push({mission:"exit",correct});if(correct){addScore(15);toast("ตอบถูก! รับดาว ⭐")}else{document.querySelector(`[data-choice="${item.answer}"]`).classList.add("correct");toast(`คำตอบคือ ${item.answer}`)}setTimeout(next,1100)})}
function renderResult(){const exitCorrect=state.answers.filter(x=>x.mission==="exit"&&x.correct).length,skill=state.answers.filter(x=>x.mission!=="exit"),skillSummary=skill.length?`${Math.round(skill.filter(x=>x.correct).length/skill.length*100)}%`:"ยังไม่ได้ทำ",passed=exitCorrect>=3;$("#missionLabel").textContent="จบการผจญภัย";$("#missionTitle").textContent="สรุปผล";$("#roundLabel").textContent="สำเร็จ";$("#progressBar").style.width="100%";$("#stage").innerHTML=`<section class="result"><div class="result-medal">${passed?"🏆":"🌟"}</div><h2>${passed?"ผู้พิชิตมาตราแม่กม":"ฝึกอีกนิดนะ"}</h2><p>แบบทดสอบท้ายคาบถูก ${exitCorrect}/5 · ภารกิจหลัก ${skillSummary}</p><div class="result-score">⭐ คะแนนรวม ${state.score}</div><p>${passed?"ได้รับสติกเกอร์ดาวดิจิทัล!":"เกณฑ์แบบทดสอบท้ายคาบคืออย่างน้อย 3 ข้อ"}</p><button id="restartButton" class="primary-button">เล่นอีกครั้ง ↻</button></section>`;$("#restartButton").onclick=()=>{sortWords.splice(0,sortWords.length,...shuffle(sortWords));pictureWords.splice(0,pictureWords.length,...shuffle(pictureWords));exitQuestions.splice(0,exitQuestions.length,...shuffle(exitQuestions));Object.assign(state,{mission:0,index:0,score:0,answers:[],busy:false,selected:[],firstTry:true});$("#score").textContent="0";render()}}

const slides=[
()=>`<span class="slide-icon">🔐</span><h2>เตรียมพร้อม<br><em>เข้าห้องเรียน</em></h2><p>ฉายรหัสห้องให้นักเรียนกรอก และตรวจรายชื่อที่เชื่อมต่อให้ครบ</p><div class="room-demo">${"000000".split("").map(x=>`<span>${x}</span>`).join("")}</div><div class="slide-actions"><a class="primary-button" href="teacher.html">เปิดจอครู</a><a class="secondary-button" href="display.html">เปิดจอโปรเจกเตอร์</a></div>`,
()=>`<div class="karaoke-box"><span class="slide-icon">🎵</span><h2>เพลง <em>มาตราแม่กม</em></h2><div class="plan-video-frame"><iframe src="https://www.youtube-nocookie.com/embed/Ut2EuUgPwbw?rel=0&playsinline=1" title="เพลงมาตราแม่กม" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><p>รอบแรก ร้องและปรบมือตามจังหวะ · รอบสอง ปรบมือเน้นคำที่มีเสียง ม ท้ายคำ</p></div>`,
()=>`<span class="slide-icon">🔎</span><h2>อ่าน ฟัง และ<em>บอกความหมาย</em></h2><p>แตะบัตรคำเพื่อฟังเสียง</p><div class="vocab-grid">${pictureWords.slice(0,4).map(x=>`<button class="vocab-card target" data-speak="${x.word}"><span>${x.emoji}</span><strong>${x.word}</strong><small>${x.hint}</small></button>`).join("")}</div>`,
()=>`<span class="slide-icon">💡</span><h2>มาตรา<em>แม่กม</em></h2><div class="rule-card">คำที่มี <strong>ม</strong> เป็นตัวสะกด<br>เมื่ออ่านจะมีเสียง <strong>“ม”</strong> อยู่ท้ายคำ</div><div class="demo-row"><span class="demo-word">ร่ม · กลม · แก้ม</span><span>เทียบกับ</span><span class="demo-word">ปลา · ธง</span></div>`,
()=>`<span class="slide-icon">🧑‍🏫</span><h2>สาธิตเกม<br><em>หนึ่งรอบ</em></h2><p>“ส้ม” มี ม เป็นตัวสะกด จึงลากลงกล่องแม่กม ส่วน “ธง” เป็นแม่กง ให้กดส่งต่อ</p><div class="demo-row"><span class="demo-word">🍊 ส้ม</span><span>→</span><span class="drop-box">📦 กล่องแม่กม</span></div>`,
()=>`<span class="slide-icon">🎮</span><h2>เริ่มสองภารกิจ<br><em>25 นาที</em></h2><p>1. กล่องคำแม่กม 10 นาที　2. ภาพนี้คำอะไร 15 นาที</p><div class="slide-actions"><button id="launchGame" class="primary-button">เปิดเกมนักเรียน</button><a class="secondary-button" href="teacher.html">ควบคุมคาบจากจอครู</a></div>`,
()=>`<span class="slide-icon">🏅</span><h2>กระดาน<em>คะแนนรวม</em></h2><p>ฉายหลังจบแต่ละภารกิจและร่วมกันชื่นชม พร้อมช่วยนักเรียนที่คะแนนต่ำกว่า 80%</p><div class="slide-actions"><a class="primary-button" href="display.html">เปิดกระดานคะแนน</a><a class="secondary-button" href="teacher.html">ดูรายละเอียดนักเรียน</a></div>`,
()=>`<span class="slide-icon">🖍️</span><h2>แผนผัง<br><em>กล่องคำแม่กม</em></h2><p>กลุ่มละ 3–4 คน เลือกคำแม่กมอย่างน้อย 5 คำ เขียนลงแผนผังและวาดภาพประกอบ 1 คำ</p><div id="classTimer" class="timer-card">15:00</div><div class="slide-actions"><button id="timerStart" class="primary-button">▶ เริ่มจับเวลา</button><button id="timerReset" class="secondary-button">↻ เริ่มใหม่</button></div><ul class="checklist"><li>□ กระดาษฟลิปชาร์ตและสีเทียน</li><li>□ แผนผังมีคำแม่กมอย่างน้อย 5 คำ</li><li>□ ตัวแทนกลุ่มอ่านออกเสียงให้เพื่อนฟัง</li></ul>`,
()=>`<span class="slide-icon">🗝️</span><h2>สรุปและ<br><em>แบบทดสอบท้ายคาบ</em></h2><div class="rule-card">มาตราแม่กม คือ คำที่มี <strong>ม</strong> เป็นตัวสะกด</div><p>ทำแบบทดสอบ 5 ข้อ เกณฑ์ผ่านอย่างน้อย 3 ข้อ</p><button id="launchExit" class="primary-button">เปิดแบบทดสอบท้ายคาบ</button>`,
()=>`<span class="slide-icon">🎉</span><h2>ผู้พิชิต<br><em>มาตราแม่กม</em></h2><div class="award-row">🥇 🥈 🥉</div><p>ฉายคะแนนและตรารางวัล มอบดาวดิจิทัล แล้วแจกใบงานที่ 3</p><div class="slide-actions"><a class="primary-button" href="display.html">ฉายผลท้ายคาบ</a><a class="secondary-button" href="worksheet-plan-3.html" target="_blank">พิมพ์ใบงานที่ 3</a></div>`,
];
function renderNav(){$("#lessonSteps").innerHTML=lessonTitles.map((x,i)=>`<li class="${i===state.slide?"active":""}" data-slide="${i}">${i+1}. ${x}</li>`).join("");document.querySelectorAll("[data-slide]").forEach(x=>x.onclick=()=>{state.slide=Number(x.dataset.slide);renderSlide()})}
function paintTimer(){const e=$("#classTimer");if(e)e.textContent=`${String(Math.floor(state.classSeconds/60)).padStart(2,"0")}:${String(state.classSeconds%60).padStart(2,"0")}`}
function renderSlide(){stopTransient();$("#slideCounter").textContent=`${state.slide+1} / 10`;$("#prevSlide").disabled=state.slide===0;$("#nextSlide").textContent=state.slide===9?"จบการสอน ✓":"ถัดไป →";$("#lessonStage").innerHTML=slides[state.slide]();renderNav();document.querySelectorAll("[data-speak]").forEach(x=>x.onclick=()=>speak(x.dataset.speak));$("#songPlay")?.addEventListener("click",()=>speak("แก้ม กลม แมงมุม ดม ทุกคำมี ม อยู่ท้าย"));$("#launchGame")?.addEventListener("click",openGame);$("#launchExit")?.addEventListener("click",()=>{openGame();clearInterval(state.roundTimer);state.roundTimer=null;state.mission=2;state.index=0;render()});$("#timerStart")?.addEventListener("click",()=>{clearInterval(state.classTimer);state.classTimer=setInterval(()=>{state.classSeconds=Math.max(0,state.classSeconds-1);paintTimer();if(!state.classSeconds)clearInterval(state.classTimer)},1000)});$("#timerReset")?.addEventListener("click",()=>{state.classSeconds=900;paintTimer()})}
function openGame(){stopTransient();$("#hero").classList.add("hidden");$("#lesson").classList.add("hidden");$("#game").classList.remove("hidden");render();scrollTo({top:0,behavior:"smooth"})}
function openLesson(){stopTransient();$("#hero").classList.add("hidden");$("#game").classList.add("hidden");$("#lesson").classList.remove("hidden");state.slide=0;renderSlide();scrollTo({top:0,behavior:"smooth"})}
$("#startButton").onclick=openGame;$("#teachButton").onclick=openLesson;$("#closeLesson").onclick=()=>{stopTransient();$("#lesson").classList.add("hidden");$("#hero").classList.remove("hidden")};$("#prevSlide").onclick=()=>{if(state.slide>0){state.slide--;renderSlide()}};$("#nextSlide").onclick=()=>{if(state.slide<9){state.slide++;renderSlide()}else{$("#lesson").classList.add("hidden");$("#hero").classList.remove("hidden")}};$("#fullscreenButton").onclick=()=>document.fullscreenElement?document.exitFullscreen():$("#lesson").requestFullscreen();
