const $=selector=>document.querySelector(selector);
const sortWords=[
  {word:"ลม",emoji:"💨",target:true},{word:"แก้ม",emoji:"😊",target:true},{word:"แมงมุม",emoji:"🕷️",target:true},{word:"ส้ม",emoji:"🍊",target:true},{word:"ร่ม",emoji:"☂️",target:true},
  {word:"กลม",emoji:"🌐",target:true},{word:"ธง",emoji:"🚩",target:false},{word:"นก",emoji:"🐦",target:false},{word:"ดาว",emoji:"⭐",target:false},{word:"ปลา",emoji:"🐟",target:false},
];
const pictureWords=[
  {word:"แก้ม",emoji:"😊",hint:"ส่วนหนึ่งของใบหน้า"},{word:"กลม",emoji:"🌐",hint:"ลักษณะเหมือนลูกบอล"},{word:"แมงมุม",emoji:"🕷️",hint:"สัตว์แปดขา"},
  {word:"ร่ม",emoji:"☂️",hint:"ใช้กันฝน"},{word:"ส้ม",emoji:"🍊",hint:"ผลไม้สีส้ม"},{word:"ลม",emoji:"💨",hint:"อากาศที่เคลื่อนที่"},
];
const exitQuestions=[
  {q:"คำใดอยู่ในมาตราแม่กม",choices:["ธง","ส้ม","ปลา"],answer:"ส้ม"},
  {q:"มาตราแม่กมมีตัวใดเป็นตัวสะกด",choices:["ง","ม","น"],answer:"ม"},
  {q:"ข้อใดเขียนสะกดคำได้ถูกต้อง",choices:["แมงมุน","แมงมูม","แมงมุม"],answer:"แมงมุม"},
];
const missions=[{title:"กล่องคำแม่กม",total:sortWords.length},{title:"ภาพนี้คำอะไร",total:pictureWords.length},{title:"Exit Ticket",total:3}];
const lessonTitles=["เข้าห้องเรียน","เพลงแม่กม","สำรวจคำศัพท์","สรุปหลักแม่กม","สาธิตเกม","เริ่ม 2 ภารกิจ","กระดานคะแนน","แผนผังกล่องคำ","สรุปและ Exit Ticket","มอบรางวัลและใบงาน"];
const state={mission:0,index:0,score:0,answers:[],busy:false,roundTimer:null,slide:0,classTimer:null,classSeconds:600,songTimer:null};
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function speak(text){if(!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="th-TH";u.rate=.75;window.speechSynthesis.speak(u)}
function toast(message){const e=$("#toast");e.textContent=message;e.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove("show"),1700)}
function stopTransient(){clearInterval(state.roundTimer);clearInterval(state.classTimer);clearInterval(state.songTimer);if("speechSynthesis"in window)window.speechSynthesis.cancel()}
function addScore(points){state.score+=points;$("#score").textContent=state.score}
function updateHeader(){const meta=missions[state.mission];$("#missionLabel").textContent=`ภารกิจ ${state.mission+1} จาก 3`;$("#missionTitle").textContent=meta.title;$("#roundLabel").textContent=`ข้อ ${Math.min(state.index+1,meta.total)} / ${meta.total}`;$("#progressBar").style.width=`${state.index/meta.total*100}%`}
function next(){clearInterval(state.roundTimer);state.index++;if(state.index>=missions[state.mission].total){state.mission++;state.index=0;if(state.mission>=3)return renderResult();addScore(5);toast("ผ่านภารกิจ! รับดาวโบนัส ⭐")}render()}
function render(){state.busy=false;updateHeader();if(state.mission===0)renderSort();if(state.mission===1)renderPicture();if(state.mission===2)renderExit()}
function resolveSort(item,answer,source){if(state.busy)return;state.busy=true;clearInterval(state.roundTimer);const correct=answer===item.target;source?.classList.add(correct?"correct":"wrong");state.answers.push({mission:"sort",correct,word:item.word});if(correct){addScore(10);toast("ถูกต้อง! กล่องเรืองแสง ✨");speak("เก่งมาก")}else toast(item.target?`${item.word} มี ม เป็นตัวสะกด`:`${item.word} ไม่ใช่คำแม่กม`);setTimeout(next,1100)}
function renderSort(){
  const item=sortWords[state.index];$("#stage").innerHTML=`<p class="instruction">ลากเฉพาะคำแม่กมลงกล่องให้ทันเวลา</p><div id="roundClock" class="round-clock">⏱️ 10 วินาที</div><div class="conveyor"><article id="movingWord" class="word-card" draggable="true"><span class="picture">${item.emoji}</span><strong>${item.word}</strong><br><button class="speak-button">🔊 ฟังคำ</button></article></div><div id="targetBox" class="drop-box">📦 กล่องคำแม่กม<br><small>คำที่มี ม เป็นตัวสะกด</small></div><div class="button-row"><button id="putWord" class="primary-button">ใส่กล่องแม่กม</button><button id="skipWord" class="secondary-button">ส่งคำนี้ต่อ</button></div>`;
  const card=$("#movingWord"),box=$("#targetBox");$(".speak-button").onclick=e=>{e.stopPropagation();speak(item.word)};card.ondragstart=e=>e.dataTransfer.setData("text/plain",item.word);box.ondragover=e=>{e.preventDefault();box.classList.add("drag-over")};box.ondragleave=()=>box.classList.remove("drag-over");box.ondrop=e=>{e.preventDefault();resolveSort(item,true,box)};$("#putWord").onclick=()=>resolveSort(item,true,$("#putWord"));$("#skipWord").onclick=()=>resolveSort(item,false,$("#skipWord"));
  let time=10;state.roundTimer=setInterval(()=>{time--;$("#roundClock").textContent=`⏱️ ${time} วินาที`;if(time<=0)resolveSort(item,false)},1000);
}
function renderPicture(){
  const item=pictureWords[state.index];$("#stage").innerHTML=`<p class="instruction">ดูภาพ อ่านคำใบ้ แล้วพิมพ์คำให้ถูกต้อง</p><div id="roundClock" class="round-clock">⏱️ 15 วินาที</div><article class="word-card"><span class="picture">${item.emoji}</span><p>${item.hint}</p><button class="speak-button" data-hint>🔊 ฟังคำใบ้</button></article><form id="pictureForm"><input id="wordAnswer" class="room-code-input" style="max-width:430px;font-size:30px;text-align:center" autocomplete="off" placeholder="พิมพ์คำจากภาพ" required><div class="choice-grid" style="margin-top:18px"><label class="choice mae-kong"><input type="radio" name="standard" value="mae-kom" required> มาตราแม่กม</label><label class="choice other"><input type="radio" name="standard" value="other"> มาตราอื่น</label></div><button class="primary-button" style="margin-top:20px">ส่งคำตอบ</button></form>`;
  $("[data-hint]").onclick=()=>speak(item.hint);$("#wordAnswer").focus();
  let time=15;state.roundTimer=setInterval(()=>{time--;$("#roundClock").textContent=`⏱️ ${time} วินาที`;if(time<=0)checkPicture(item,true)},1000);
  $("#pictureForm").onsubmit=e=>{e.preventDefault();checkPicture(item,false)};
}
function checkPicture(item,timedOut){if(state.busy)return;state.busy=true;clearInterval(state.roundTimer);const typed=$("#wordAnswer").value.trim(),standard=document.querySelector('input[name="standard"]:checked')?.value;const wordCorrect=typed===item.word,standardCorrect=standard==="mae-kom",correct=wordCorrect&&standardCorrect;state.answers.push({mission:"picture",word:item.word,correct});if(correct){addScore(20);toast("สะกดถูกและเลือกมาตราถูก! 🏅");speak(item.word)}else toast(timedOut?`หมดเวลา คำตอบคือ ${item.word} · แม่กม`:`คำตอบคือ ${item.word} และอยู่ในมาตราแม่กม`);setTimeout(next,1400)}
function renderExit(){const item=exitQuestions[state.index];$("#stage").innerHTML=`<article class="exit-question"><span class="eyebrow">Exit Ticket ข้อที่ ${state.index+1}</span><h2>${item.q}</h2><div class="exit-options">${item.choices.map(c=>`<button data-choice="${c}">${c}</button>`).join("")}</div></article>`;document.querySelectorAll("[data-choice]").forEach(button=>button.onclick=()=>{if(state.busy)return;state.busy=true;const correct=button.dataset.choice===item.answer;button.classList.add(correct?"correct":"wrong");state.answers.push({mission:"exit",correct});if(correct){addScore(15);toast("ตอบถูก! รับดาว ⭐")}else{document.querySelector(`[data-choice="${item.answer}"]`).classList.add("correct");toast(`คำตอบคือ ${item.answer}`)}setTimeout(next,1100)})}
function renderResult(){const exitCorrect=state.answers.filter(x=>x.mission==="exit"&&x.correct).length,skill=state.answers.filter(x=>x.mission!=="exit"),skillPercent=Math.round(skill.filter(x=>x.correct).length/skill.length*100),passed=exitCorrect>=2;$("#missionLabel").textContent="จบการผจญภัย";$("#missionTitle").textContent="สรุปผล";$("#roundLabel").textContent="สำเร็จ";$("#progressBar").style.width="100%";$("#stage").innerHTML=`<section class="result"><div class="result-medal">${passed?"🏆":"🌟"}</div><h2>${passed?"ผู้พิชิตมาตราแม่กม":"ฝึกอีกนิดนะ"}</h2><p>Exit Ticket ถูก ${exitCorrect}/3 · ภารกิจหลัก ${skillPercent}%</p><div class="result-score">⭐ คะแนนรวม ${state.score}</div><p>${passed?"ได้รับสติกเกอร์ดาวดิจิทัล!":"เกณฑ์ Exit Ticket คืออย่างน้อย 2 ข้อ"}</p><button id="restartButton" class="primary-button">เล่นอีกครั้ง ↻</button></section>`;$("#restartButton").onclick=()=>{Object.assign(state,{mission:0,index:0,score:0,answers:[],busy:false});$("#score").textContent="0";render()}}

const slides=[
()=>`<span class="slide-icon">🔐</span><h2>เตรียมพร้อม<br><em>เข้าห้องเรียน</em></h2><p>ฉาย Room Code ให้นักเรียนกรอก และตรวจรายชื่อที่เชื่อมต่อให้ครบ</p><div class="room-demo">${"000000".split("").map(x=>`<span>${x}</span>`).join("")}</div><div class="slide-actions"><a class="primary-button" href="teacher.html">เปิด Teacher Dashboard</a><a class="secondary-button" href="display.html">เปิดจอโปรเจกเตอร์</a></div>`,
()=>`<div class="karaoke-box"><span class="slide-icon">🎵</span><h2>เพลง <em>แม่กม</em></h2><p>สื่อในแผนระบุเพลง “แม่กม” ผู้สร้างสรรค์: พี่กุดจี่</p><p class="karaoke-line">แก้ม กลม แมงมุม ดม</p><p class="karaoke-line">ทุกคำมี ม อยู่ท้าย</p><button id="songPlay" class="primary-button">▶ ร้องทบทวนคำ</button><small style="display:block;margin-top:15px">ใช้บททบทวนนี้เมื่อยังไม่ได้เพิ่มไฟล์เพลงต้นฉบับ</small></div>`,
()=>`<span class="slide-icon">🔎</span><h2>อ่าน ฟัง และ<em>บอกความหมาย</em></h2><p>แตะบัตรคำเพื่อฟังเสียง</p><div class="vocab-grid">${pictureWords.slice(0,4).map(x=>`<button class="vocab-card target" data-speak="${x.word}"><span>${x.emoji}</span><strong>${x.word}</strong><small>${x.hint}</small></button>`).join("")}</div>`,
()=>`<span class="slide-icon">💡</span><h2>มาตรา<em>แม่กม</em></h2><div class="rule-card">คำที่มี <strong>ม</strong> เป็นตัวสะกด<br>เมื่ออ่านจะมีเสียง <strong>“ม”</strong> อยู่ท้ายคำ</div><div class="demo-row"><span class="demo-word">ร่ม · กลม · แก้ม</span><span>เทียบกับ</span><span class="demo-word">ปลา · ธง</span></div>`,
()=>`<span class="slide-icon">🧑‍🏫</span><h2>สาธิตเกม<br><em>หนึ่งรอบ</em></h2><p>“ส้ม” มี ม เป็นตัวสะกด จึงลากลงกล่องแม่กม ส่วน “ธง” เป็นแม่กง ให้กดส่งต่อ</p><div class="demo-row"><span class="demo-word">🍊 ส้ม</span><span>→</span><span class="drop-box">📦 กล่องแม่กม</span></div>`,
()=>`<span class="slide-icon">🎮</span><h2>เริ่มสองภารกิจ<br><em>30 นาที</em></h2><p>1. กล่องคำแม่กม 　2. ภาพนี้คำอะไร</p><div class="slide-actions"><button id="launchGame" class="primary-button">เปิดเกมนักเรียน</button><a class="secondary-button" href="teacher.html">ควบคุมคาบจากจอครู</a></div>`,
()=>`<span class="slide-icon">🏅</span><h2>กระดาน<em>คะแนนรวม</em></h2><p>ฉายหลังจบแต่ละภารกิจและร่วมกันชื่นชม พร้อมช่วยนักเรียนที่คะแนนต่ำกว่า 80%</p><div class="slide-actions"><a class="primary-button" href="display.html">เปิด Leaderboard</a><a class="secondary-button" href="teacher.html">ดูรายละเอียดนักเรียน</a></div>`,
()=>`<span class="slide-icon">🖍️</span><h2>แผนผัง<br><em>กล่องคำแม่กม</em></h2><p>กลุ่มละ 3–4 คน วาดกล่องกลางกระดาษ แล้วเขียนคำแม่กมล้อมรอบให้ได้มากที่สุด</p><div id="classTimer" class="timer-card">10:00</div><div class="slide-actions"><button id="timerStart" class="primary-button">▶ เริ่มจับเวลา</button><button id="timerReset" class="secondary-button">↻ เริ่มใหม่</button></div><ul class="checklist"><li>□ กระดาษฟลิปชาร์ตและสีเทียน</li><li>□ อ่านคำของกลุ่ม 1–2 คำ</li><li>□ บอกความหมายและตรวจการสะกด</li></ul>`,
()=>`<span class="slide-icon">🗝️</span><h2>สรุปและ<br><em>Exit Ticket</em></h2><div class="rule-card">มาตราแม่กม คือ คำที่มี <strong>ม</strong> เป็นตัวสะกด</div><p>ทำ Exit Ticket 3 ข้อ เกณฑ์ผ่านอย่างน้อย 2 ข้อ</p><button id="launchExit" class="primary-button">เปิด Exit Ticket</button>`,
()=>`<span class="slide-icon">🎉</span><h2>ผู้พิชิต<br><em>มาตราแม่กม</em></h2><div class="award-row">🥇 🥈 🥉</div><p>ฉายคะแนนและ Badge มอบดาวดิจิทัล แล้วแจกใบงานที่ 3</p><div class="slide-actions"><a class="primary-button" href="display.html">ฉายผลท้ายคาบ</a><a class="secondary-button" href="worksheet-plan-3.html" target="_blank">พิมพ์ใบงานที่ 3</a></div>`,
];
function renderNav(){$("#lessonSteps").innerHTML=lessonTitles.map((x,i)=>`<li class="${i===state.slide?"active":""}" data-slide="${i}">${i+1}. ${x}</li>`).join("");document.querySelectorAll("[data-slide]").forEach(x=>x.onclick=()=>{state.slide=Number(x.dataset.slide);renderSlide()})}
function paintTimer(){const e=$("#classTimer");if(e)e.textContent=`${String(Math.floor(state.classSeconds/60)).padStart(2,"0")}:${String(state.classSeconds%60).padStart(2,"0")}`}
function renderSlide(){stopTransient();$("#slideCounter").textContent=`${state.slide+1} / 10`;$("#prevSlide").disabled=state.slide===0;$("#nextSlide").textContent=state.slide===9?"จบการสอน ✓":"ถัดไป →";$("#lessonStage").innerHTML=slides[state.slide]();renderNav();document.querySelectorAll("[data-speak]").forEach(x=>x.onclick=()=>speak(x.dataset.speak));$("#songPlay")?.addEventListener("click",()=>speak("แก้ม กลม แมงมุม ดม ทุกคำมี ม อยู่ท้าย"));$("#launchGame")?.addEventListener("click",openGame);$("#launchExit")?.addEventListener("click",()=>{openGame();state.mission=2;state.index=0;render()});$("#timerStart")?.addEventListener("click",()=>{clearInterval(state.classTimer);state.classTimer=setInterval(()=>{state.classSeconds=Math.max(0,state.classSeconds-1);paintTimer();if(!state.classSeconds)clearInterval(state.classTimer)},1000)});$("#timerReset")?.addEventListener("click",()=>{state.classSeconds=600;paintTimer()})}
function openGame(){stopTransient();$("#hero").classList.add("hidden");$("#lesson").classList.add("hidden");$("#game").classList.remove("hidden");render();scrollTo({top:0,behavior:"smooth"})}
function openLesson(){stopTransient();$("#hero").classList.add("hidden");$("#game").classList.add("hidden");$("#lesson").classList.remove("hidden");state.slide=0;renderSlide();scrollTo({top:0,behavior:"smooth"})}
$("#startButton").onclick=openGame;$("#teachButton").onclick=openLesson;$("#closeLesson").onclick=()=>{stopTransient();$("#lesson").classList.add("hidden");$("#hero").classList.remove("hidden")};$("#prevSlide").onclick=()=>{if(state.slide>0){state.slide--;renderSlide()}};$("#nextSlide").onclick=()=>{if(state.slide<9){state.slide++;renderSlide()}else{$("#lesson").classList.add("hidden");$("#hero").classList.remove("hidden")}};$("#fullscreenButton").onclick=()=>document.fullscreenElement?document.exitFullscreen():$("#lesson").requestFullscreen();
