import {shuffle,parseRoster,distribute,totals,escapeHTML,validateBank} from './core.js';
const $=s=>document.querySelector(s),esc=escapeHTML,KEY='rt-learning-classroom-v1';
const CATEGORIES=[
['oral-word','อ่านออกเสียง · คำ','ฝึกสะกด อ่านชัด ถูกต้อง','ก','#e5eedf','#498761'],
['oral-sentence','อ่านออกเสียง · ประโยค','อ่านต่อเนื่องและเว้นวรรค','≋','#fff0d8','#ba923c'],
['oral-passage','อ่านออกเสียง · ข้อความ','อ่านคล่อง เข้าใจจังหวะ','☷','#e5efee','#498779'],
['picture-word','คำกับภาพ','อ่านคำ แล้วเลือกภาพที่ตรงกัน','▧','#fbe7dc','#cb865c'],
['word-meaning','ความหมายของคำ','เชื่อมคำกับความหมาย','↔','#f3e8ee','#ae7292'],
['picture-writing','เขียนเล่าเรื่องจากภาพ','ใช้ประโยคง่าย ๆ สื่อความ','✎','#fff0d8','#ba923c'],
['sentence-comprehension','เข้าใจประโยค','อ่านข้อมูล คิด และตอบ','?','#e5eedf','#498761'],
['passage-comprehension','เข้าใจข้อความ','ลำดับเหตุการณ์ เหตุผล ข้อคิด','▤','#e7ebf7','#7d86b8']];
const categoryName=id=>CATEGORIES.find(c=>c[0]===id)?.[1]||id;
let state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}
if(!state||!Array.isArray(state.roster))state={name:'ห้องเรียนอ่านสนุก',roster:[],teams:[],events:[],ink:{},used:[],mode:'class',selected:null};
state.events||=[];state.teams||=[];state.ink||={};state.used||=[];
let catalog=[],banks=new Map(),category='',pageSize=16,deck=[],index=0,round=crypto.randomUUID(),activity='teach',completed=false,clock=0,ticking=false,lastTick=0,inkMode='pointer',undo=[],redo=[],stroke=null,erasing=false,toastTimer,cloud=null,cloudRoom=null,dialogTab='roster',loadError='',activeInkId='';
const drawing=$('#ink');
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('พื้นที่บันทึกบนเครื่องเต็ม กรุณาส่งออกข้อมูลห้องเรียน')}}
function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200)}
function modal(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal()}
function closeModal(){$('#dialog').close()}
function filtered(){const term=$('#search').value.trim().toLowerCase(),year=$('#year').value,form=$('#form').value,tag=$('#tag').value;return catalog.filter(q=>(!category||q.category===category)&&(!year||q.year===+year)&&(!form||q.form===+form)&&(!tag||q.tags.includes(tag))&&(!$('#auto-only').checked||q.auto)&&(!term||[q.prompt,...q.tags,categoryName(q.category),q.year].join(' ').toLowerCase().includes(term)))}
function renderLibrary(){const rows=filtered();$('#stat-questions').textContent=catalog.length.toLocaleString('th-TH');$('#result-title').textContent=category?categoryName(category):'ข้อคำถามทั้งหมด';$('#result-count').textContent=loadError||`${rows.length.toLocaleString('th-TH')} ข้อ · เลือกข้อที่อยากเริ่ม หรือเปิดเป็นชุดฝึก`;
$('#category-grid').innerHTML=CATEGORIES.map(([id,name,desc,icon,tint,tone])=>`<button class="category-card ${category===id?'chosen':''}" data-category="${id}" aria-pressed="${category===id}" style="--tint:${tint};--tone:${tone}"><span class="count">${catalog.filter(q=>q.category===id).length} ข้อ</span><span class="category-icon">${icon}</span><h3>${name}</h3><p>${desc}</p></button>`).join('');
$('#question-list').innerHTML=rows.length?rows.slice(0,pageSize).map(q=>`<button class="question-card" data-question="${esc(q.id)}"><span class="q-thumb">${q.category==='oral-word'?esc(q.prompt[0]):esc(CATEGORIES.find(c=>c[0]===q.category)?.[3]||'ก')}</span><div><small>ปี ${q.year} · รูปแบบ ${q.form} · ข้อ ${esc(q.no)}</small><h4>${esc(q.prompt)}</h4><span class="q-tag">${esc(q.tags.slice(0,2).join(' · '))}</span></div><span class="arrow">↗</span></button>`).join(''):`<div class="empty-state">${catalog.length?'ไม่พบข้อที่ตรงกับตัวกรอง<br>ลองเปลี่ยนปี หมวด หรือคำค้น':'ยังไม่มีคลังข้อคำถามในเว็บไซต์<br>นำเข้าไฟล์คลังข้อสอบผ่านเมนูข้อมูลข้อสอบได้'}</div>`;$('#load-more').hidden=rows.length<=pageSize}
function rebuildFilters(){const oldYear=$('#year').value,oldTag=$('#tag').value;$('#year').innerHTML='<option value="">รวมทุกปี</option>'+[...new Set(catalog.map(q=>q.year))].sort((a,b)=>b-a).map(y=>`<option>${y}</option>`).join('');$('#year').value=oldYear;$('#tag').innerHTML='<option value="">ทุกทักษะย่อย</option>'+[...new Set(catalog.flatMap(q=>q.tags))].sort().map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');$('#tag').value=oldTag}
async function init(){try{const r=await fetch('data/catalog.json');if(!r.ok)throw Error('คลังข้อคำถามยังไม่ถูกติดตั้ง');const j=await r.json();catalog=j.questions||[];loadError=catalog.length?'':'คลังข้อสอบจริงรอการนำเข้าหรืออนุมัติเผยแพร่'}catch(e){loadError=e.message}rebuildFilters();renderLibrary();updateTotals();if(location.hash.includes('access_token')||location.search.includes('code='))await cloudUI()}
async function getBank(id){if(banks.has(id))return banks.get(id);const r=await fetch('data/'+id+'.json');if(!r.ok)throw Error('ไม่พบไฟล์ข้อสอบชุดนี้ กรุณานำเข้าคลังก่อน');const b=validateBank(await r.json());banks.set(id,b);return b}
function home(){save();ticking=false;$('#home-view').hidden=false;$('#teach-view').hidden=true;document.body.classList.remove('projection');window.scrollTo({top:0});renderLibrary()}
async function start(qid){let rows=filtered();if(qid){const selected=rows.find(q=>q.id===qid);if(!selected)return;rows=[selected,...rows.filter(q=>q.id!==qid)]}if(!rows.length){toast('เลือกหรือนำเข้าข้อคำถามก่อนเริ่ม');return}if($('#shuffle').checked&&!qid)rows=shuffle(rows);const limit=$('#limit').value;deck=rows.slice(0,limit==='all'?rows.length:+limit);index=0;round=crypto.randomUUID();completed=false;activity=$('#activity').value;clock=0;ticking=false;$('#next').disabled=false;$('#reveal').disabled=false;$('#home-view').hidden=true;$('#teach-view').hidden=false;window.scrollTo({top:0});await showQuestion()}
function current(){return deck[index]}
function recipient(){if(state.mode==='individual'){const p=state.roster.find(p=>p.id===state.selected&&p.active!==false);return p?{id:p.id,label:p.number+'. '+p.name,type:'individual'}:null}if(state.mode==='team'){const t=state.teams.find(t=>t.id===state.selected);return t?{id:t.id,label:t.name,type:'team'}:null}return {id:'class',label:'ฝึกพร้อมกันทั้งห้อง',type:'class'}}
async function showQuestion(){if(!current())return;const requested=current().id;save();$('#feedback').hidden=true;$('#solution').hidden=true;$('#solution').open=false;$('#question-content').innerHTML='<div class="skeleton">กำลังเปิดข้อคำถาม…</div>';$('#answer-controls').replaceChildren();drawing.classList.remove('drawing');$('#lesson-meta').textContent=`ปี ${current().year} · รูปแบบที่ ${current().form} · ข้อ ${current().no}`;$('#lesson-title').textContent=categoryName(current().category);$('#lesson-count').textContent=`ข้อ ${index+1} / ${deck.length}`;$('#progress-bar').style.width=(index+1)/deck.length*100+'%';$('#previous').disabled=index===0;$('#next').textContent=index===deck.length-1?'จบกิจกรรม ✓':'ข้อถัดไป →';
try{const b=await getBank(current().year+'-'+current().form);if(current()?.id!==requested)return;const q=b.questions.find(q=>q.id===requested);if(!q)throw Error('ข้อมูลข้อนี้ไม่ครบ');deck[index]={...q,auto:!!q.answer};const image=q.image?b.assets[q.image]:null;$('#question-content').innerHTML=`<div class="source-badge"><span>${q.subject==='oral'?'อ่านออกเสียง':'อ่านรู้เรื่อง'} · ข้อ ${esc(q.no)}</span><span>ต้นฉบับหน้า ${q.source.page}</span></div>${q.category==='picture-word'?`<div class="target-word">${esc(q.prompt)}</div>`:''}${image?`<img class="stimulus-image" src="${image}" alt="โจทย์ต้นฉบับ ปี ${q.year} รูปแบบ ${q.form} ข้อ ${esc(q.no)}">`:`<div class="${q.category==='oral-word'?'word-stimulus':'passage-stimulus'}">${esc(q.prompt)}</div>`}`;
if(image)await $('#question-content img').decode().catch(()=>{});if(current()?.id!==requested)return;
const manual=q.subject==='oral'||!q.answer;$('#answer-controls').innerHTML=(q.category==='picture-writing'?'<textarea id="written-response" class="written-answer" placeholder="เขียนประโยคจากภาพที่นี่ หรือใช้ปากกาเขียนบนจอ" aria-label="คำตอบจากภาพ"></textarea>':'')+(q.choices.length?`<div class="manual-label">${q.category==='picture-word'?'เลือกตัวอักษรใต้ภาพที่ตรงกับคำ':manual?'เลือกคำตอบเพื่ออภิปรายร่วมกัน · ครูตรวจให้คะแนน':'เลือกคำตอบที่ถูกต้อง'}</div>`+q.choices.map(c=>`<button class="choice" data-choice="${esc(c)}">${esc(c)}</button>`).join(''):'')+(manual?`<div class="manual-controls"><span class="manual-label">${q.subject==='oral'?'ครูฟังการอ่าน แล้วให้ดาวตามกิจกรรม':'ครูประเมินคำตอบ · ข้อนี้ไม่มีการตรวจอัตโนมัติ'} · เต็ม ${q.maxPoints} ดาว</span>${Array.from({length:q.maxPoints+1},(_,i)=>`<button class="manual-score" data-score="${i}">${i===0?'ฝึกอีกนิด':i+' ★'}</button>`).join('')}</div>`:'');
$('#solution-content').innerHTML=`${q.answer?`<p><b>คำตอบ: ${esc(q.answer)}</b></p>`:''}${q.reading?`<p>คำอ่าน: ${esc(q.reading)}</p>`:''}<p>${esc(q.explanation|| (q.category==='picture-writing'?'ประเมินการเขียนให้สื่อความตรงกับภาพและเป็นประโยค ตรวจเกณฑ์ของปีนั้นก่อนให้คะแนนประเมิน RT':'ยังไม่มีเฉลยที่ยืนยันในข้อมูลข้อนี้ ให้ครูตรวจคำตอบหรือฟังการอ่าน'))}</p><p class="database-note">ต้นฉบับ: ${esc(q.source.file)} · หน้า ${q.source.page}${q.keySource?`<br>ฉบับครู: ${esc(q.keySource.file)} · หน้า ${q.keySource.page}`:''}<br>หมวดย่อย: ${esc(q.tags.join(' · '))}</p>`;
activeInkId=q.id;state.ink[activeInkId]||=[];undo=[];redo=[];drawing.setAttribute('viewBox','0 0 1000 1000');drawing.setAttribute('preserveAspectRatio','none');paint();setTool(inkMode);updateTotals();applyRecordedState()
}catch(e){$('#question-content').innerHTML='<div class="empty-state">'+esc(e.message)+'</div>';toast(e.message)}}
function updateTotals(){const r=recipient(),all=totals(state.events);$('#answerer-label').textContent=r?.label||'กรุณาเลือกผู้ตอบ';$('#game-points').textContent=all.get(r?.id||'class')?.points||0;$('#game-status').textContent=activity==='quiz'?'ท้าทายเก็บดาว · ให้ทุกคนมีส่วนร่วม':'คะแนนกิจกรรม · ฝึกพร้อมกัน';$('#mini-leaderboard').innerHTML=state.teams.map(t=>({...t,points:all.get(t.id)?.points||0})).sort((a,b)=>b.points-a.points).slice(0,4).map(t=>`<div class="mini-team"><span>${esc(t.name)}</span><b>${t.points} ★</b></div>`).join('')}
function eventKey(){const r=recipient();return r&&current()?round+':'+current().id+':'+r.id:null}
function applyRecordedState(){const event=state.events.find(e=>e.key===eventKey());if(!event)return;document.querySelectorAll('[data-score]').forEach(b=>b.disabled=true);if(current().answer)document.querySelectorAll('[data-choice]').forEach(b=>{b.disabled=true;b.classList.toggle('correct',b.dataset.choice===current().answer);b.classList.toggle('wrong',b.dataset.choice===event.response&&event.points===0)});$('#feedback').hidden=false;$('#feedback').classList.toggle('error',event.points===0);$('#feedback').textContent=`บันทึกแล้ว: ${event.label} · ${event.points} / ${event.maxPoints} ดาว`}
function score(points,response=''){const q=current(),r=recipient();if(!q||!r){toast('เลือกผู้ตอบหรือกลุ่มในห้องเรียนก่อนให้คะแนน');return}if(state.events.some(e=>e.key===eventKey())){toast('บันทึกข้อนี้แล้ว ใช้ย้อนกลับคะแนนหากต้องการแก้ไข');return}state.events.push({id:crypto.randomUUID(),key:eventKey(),round,qid:q.id,year:q.year,form:q.form,no:q.no,category:q.category,target:r.id,label:r.label,type:r.type,points,maxPoints:q.maxPoints,response,at:new Date().toISOString()});save();updateTotals();applyRecordedState();if(points>0&&activity==='quiz')celebrate()}
function choose(value){document.querySelectorAll('[data-choice]').forEach(b=>b.classList.toggle('selected',b.dataset.choice===value));if(current().answer)score(value===current().answer?current().maxPoints:0,value);else toast('เลือก '+value+' แล้ว · ครูตรวจและให้ดาวด้านล่าง')}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<22;i++){const s=document.createElement('i');s.className='confetti-bit';s.style.left=Math.random()*100+'vw';s.style.background=['#e7784f','#e7b448','#4c8b6a'][i%3];s.style.animationDelay=Math.random()*.3+'s';$('#confetti').append(s);setTimeout(()=>s.remove(),2200)}}
function finish(){save();ticking=false;completed=true;const events=state.events.filter(e=>e.round===round);$('#question-content').innerHTML=`<div class="completed"><span class="eyebrow">เก่งขึ้นอีกหนึ่งก้าว</span><h2>จบกิจกรรมแล้ว!</h2><strong>★ ${events.reduce((s,e)=>s+e.points,0)}</strong><p>บันทึกคำตอบ ${events.length} ครั้ง จากชุดฝึก ${deck.length} ข้อ<br>ทุกความพยายามมีคุณค่า มาฝึกต่อด้วยกันนะ</p><button class="primary" data-action="scoreboard">ดูผลกิจกรรม →</button></div>`;$('#answer-controls').replaceChildren();$('#feedback').hidden=true;$('#solution').hidden=true;drawing.replaceChildren();drawing.classList.remove('drawing');$('#next').disabled=true;$('#reveal').disabled=true}
async function next(){if(index<deck.length-1){index++;await showQuestion()}else finish()}
async function previous(){if(completed){completed=false;$('#next').disabled=false;$('#reveal').disabled=false;await showQuestion();return}if(index>0){index--;await showQuestion()}}
function setTool(tool){inkMode=tool;drawing.classList.toggle('drawing',tool!=='pointer'&&!completed);document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('selected',b.dataset.tool===tool);b.setAttribute('aria-pressed',String(b.dataset.tool===tool))})}
function inkRows(){return state.ink[activeInkId]||[]}
function paint(){drawing.replaceChildren();for(const s of inkRows()){const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');for(const [a,v]of Object.entries({points:s.points.map(p=>p.join(',')).join(' '),fill:'none',stroke:s.color,'stroke-width':s.width,'stroke-linecap':'round','stroke-linejoin':'round',opacity:s.alpha||1,'vector-effect':'non-scaling-stroke'}))line.setAttribute(a,v);drawing.append(line)}}
function rememberInk(){undo.push(structuredClone(inkRows()));if(undo.length>40)undo.shift();redo=[]}
function point(e){const r=drawing.getBoundingClientRect();return [(e.clientX-r.left)/r.width*1000,(e.clientY-r.top)/r.height*1000]}
function erase(p){state.ink[activeInkId]=inkRows().filter(s=>!s.points.some((q,i)=>{const a=s.points[Math.max(0,i-1)],dx=q[0]-a[0],dy=q[1]-a[1],len=dx*dx+dy*dy,t=len?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/len)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy)<22}));paint()}
drawing.onpointerdown=e=>{if(inkMode==='pointer'||completed||!activeInkId)return;e.preventDefault();drawing.setPointerCapture(e.pointerId);rememberInk();const p=point(e);if(inkMode==='eraser'){erasing=true;erase(p)}else{stroke={points:[p,[p[0]+.05,p[1]+.05]],color:$('#ink-color').value,width:+$('#ink-width').value*(inkMode==='highlight'?4:1),alpha:inkMode==='highlight'?.3:1};state.ink[activeInkId].push(stroke);paint()}};
drawing.onpointermove=e=>{if(erasing){erase(point(e));return}if(!stroke)return;stroke.points.push(point(e));paint()};
drawing.onpointerup=drawing.onpointercancel=()=>{stroke=null;erasing=false;save()};
function undoInk(){if(undo.length){redo.push(structuredClone(inkRows()));state.ink[activeInkId]=undo.pop();paint();save()}}
function redoInk(){if(redo.length){undo.push(structuredClone(inkRows()));state.ink[activeInkId]=redo.pop();paint();save()}}
function classroom(tab=dialogTab){dialogTab=tab;modal(state.name,`<div class="dialog-tabs">${[['roster','รายชื่อ'],['teams','จัดกลุ่ม'],['scores','คะแนน'],['backup','บันทึก / ส่งออก']].map(([t,l])=>`<button data-tab="${t}" class="${tab===t?'active':''}">${l}</button>`).join('')}</div><div id="class-body"></div>`);if(tab==='roster')rosterUI();if(tab==='teams')teamsUI();if(tab==='scores')scoresUI();if(tab==='backup')backupUI()}
function rosterUI(){$('#class-body').innerHTML=`<p class="dialog-help">ใส่รายชื่อหนึ่งคนต่อบรรทัด เช่น “1 สมชาย” หรือใส่เฉพาะชื่อ<br>ติ๊กชื่อคนที่มาเรียน เพื่อใช้สุ่มและจัดกลุ่ม</p><textarea id="roster-editor" class="roster-editor" aria-label="รายชื่อนักเรียน">${esc(state.roster.map(p=>p.number+' '+p.name).join('\n'))}</textarea><div class="dialog-actions"><button class="primary" data-action="save-roster">บันทึกรายชื่อ</button><button class="secondary" data-action="number-roster">ใช้เลขที่ 1–…</button><button class="secondary" data-action="import-p1">นำเข้าห้องเรียน ป.1 เดิม</button></div><div class="roster-list">${state.roster.map(p=>`<label class="roster-row"><input type="checkbox" data-attendance="${esc(p.id)}" ${p.active!==false?'checked':''}><span>${p.number}. ${esc(p.name)}</span></label>`).join('')}</div><hr><label class="dialog-help">ผู้รับคะแนน<select id="recipient-mode"><option value="class">ทั้งห้อง</option><option value="individual">รายบุคคล</option><option value="team">รายกลุ่ม</option></select></label><select id="recipient-select" aria-label="เลือกผู้ตอบ"></select>`;$('#recipient-mode').value=state.mode;recipientOptions()}
function recipientOptions(){const el=$('#recipient-select');if(!el)return;const mode=$('#recipient-mode').value,items=mode==='individual'?state.roster.filter(p=>p.active!==false).map(p=>({id:p.id,name:p.number+'. '+p.name})):mode==='team'?state.teams:[];el.innerHTML='<option value="">เลือกผู้ตอบ / กลุ่ม</option>'+items.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}</option>`).join('');el.value=state.selected||'';el.hidden=mode==='class'}
function saveRoster(){try{state.roster=parseRoster($('#roster-editor').value,state.roster);state.used=[];state.teams.forEach(t=>t.members=t.members.filter(id=>state.roster.some(p=>p.id===id)));save();classroom('roster');updateTotals();toast('บันทึกรายชื่อแล้ว')}catch(e){toast(e.message)}}
function teamsUI(){$('#class-body').innerHTML=`<p class="dialog-help">จัดกลุ่มเฉพาะผู้ที่มาเรียน สมาชิกแต่ละกลุ่มใกล้เคียงกัน เปลี่ยนชื่อและย้ายสมาชิกได้</p><div class="form-row"><label>จำนวนกลุ่ม<input id="team-count" class="form-input" type="number" min="2" max="10" value="${state.teams.length||3}"></label><label>วิธีแบ่ง<select id="team-method"><option value="random">สุ่มสมาชิก</option><option value="number">ตามลำดับเลขที่</option></select></label></div><div class="dialog-actions"><button class="primary" data-action="divide-teams">จัดกลุ่มใหม่</button></div>${state.teams.map(t=>`<div class="team-card"><input class="form-input" data-team-name="${esc(t.id)}" maxlength="60" aria-label="ชื่อกลุ่ม" value="${esc(t.name)}"><p>${t.members.map(id=>{const p=state.roster.find(p=>p.id===id);return p?p.number+'. '+esc(p.name):''}).filter(Boolean).join(' · ')||'ยังไม่มีสมาชิก'}</p><button class="text-button" data-select-team="${esc(t.id)}">ให้กลุ่มนี้ตอบ →</button></div>`).join('')}<label class="dialog-help">ย้ายสมาชิก<select id="move-pupil"><option value="">เลือกสมาชิก</option>${state.roster.filter(p=>p.active!==false).map(p=>`<option value="${esc(p.id)}">${p.number}. ${esc(p.name)}</option>`).join('')}</select></label><select id="move-team" aria-label="ย้ายไปกลุ่ม"><option value="">เลือกกลุ่มปลายทาง</option>${state.teams.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select><div class="dialog-actions"><button class="secondary" data-action="move-pupil">ย้ายสมาชิก</button></div>`}
function divide(){try{const groups=distribute(state.roster,+$('#team-count').value,$('#team-method').value==='random');state.teams=groups.map((members,i)=>({id:crypto.randomUUID(),name:['ทีมใบไม้','ทีมแสงแดด','ทีมสายรุ้ง','ทีมดอกไม้','ทีมดวงดาว'][i]||'ทีม '+(i+1),members:members.map(p=>p.id)}));state.mode='team';state.selected=state.teams[0].id;save();classroom('teams');updateTotals()}catch(e){toast(e.message)}}
function scoreEntries(){return [...totals(state.events).values()].sort((a,b)=>b.points-a.points)}
function scoresUI(){$('#class-body').innerHTML=`<p class="dialog-help">ดาวสะสมจากกิจกรรมทั้งหมดบนเครื่องนี้ · แยกรายคน รายกลุ่ม และทั้งห้อง</p>${scoreEntries().map((e,i)=>`<div class="score-row"><span>${i+1}</span><span>${esc(e.label)}</span><strong>${e.points} ★</strong><div class="score-adjust"><button data-adjust="${esc(e.id)}" data-delta="-1" aria-label="ลดดาว">−</button><button data-adjust="${esc(e.id)}" data-delta="1" aria-label="เพิ่มดาว">+</button></div></div>`).join('')||'<div class="empty-state">ยังไม่มีคะแนน เริ่มกิจกรรมแล้วให้ดาวได้เลย</div>'}<div class="dialog-actions"><button class="secondary" data-action="undo-score">↶ ย้อนกลับคะแนนล่าสุด</button><button class="primary" data-action="export-csv">ส่งออกคะแนน CSV</button></div><p class="database-note">ดาวกิจกรรมใช้สร้างแรงจูงใจ ไม่ใช่คะแนนประเมิน RT อย่างเป็นทางการ</p>`}
function adjust(id,delta){const t=scoreEntries().find(e=>e.id===id);if(!t)return;state.events.push({id:crypto.randomUUID(),key:crypto.randomUUID(),round:null,qid:null,target:id,label:t.label,type:t.type,points:delta,maxPoints:0,response:'ปรับคะแนนโดยครู',at:new Date().toISOString()});save();classroom('scores');updateTotals()}
function undoScore(){const last=state.events.pop();if(!last)return;save();updateTotals();classroom('scores');toast('ย้อนกลับคะแนนของ '+last.label+' แล้ว');if(!$('#teach-view').hidden&&!completed)showQuestion()}
function backupUI(){$('#class-body').innerHTML=`<label class="dialog-help">ชื่อห้องเรียน<input id="room-name" class="form-input" maxlength="100" value="${esc(state.name)}"></label><div class="dialog-actions"><button class="secondary" data-action="rename-room">บันทึกชื่อ</button><button class="primary" data-action="export-backup">ดาวน์โหลดข้อมูลห้องเรียน</button></div><label class="import-file">นำเข้าข้อมูลห้องเรียนที่สำรองไว้<input id="import-backup" type="file" accept=".json,application/json"></label><div class="status-box">${cloudRoom?'เชื่อมกับ '+esc(cloudRoom.name):'ข้อมูลบันทึกบนเบราว์เซอร์เครื่องนี้'}</div><div class="dialog-actions"><button class="primary" data-action="cloud-save">บันทึกห้องนี้บน Supabase</button><button class="secondary" data-action="cloud">เลือกห้องจาก Supabase</button></div><p class="database-note">ข้อมูลห้องเรียนบน Supabase เข้าถึงได้เฉพาะเจ้าของห้อง</p>`}
function download(name,content,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCSV(){const cell=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^([=+\-@])/,"'$1")+'"';const header=['เวลา','ปี','รูปแบบ','เลขข้อ','หมวด','ผู้ตอบ','รูปแบบคะแนน','ดาวที่ได้','ดาวเต็ม','คำตอบ'];const rows=state.events.map(e=>[e.at,e.year,e.form,e.no,categoryName(e.category),e.label,e.type,e.points,e.maxPoints,e.response]);download('RT-คะแนนกิจกรรม.csv','\uFEFF'+[header,...rows].map(row=>row.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
function randomPanel(){modal('สุ่มผู้ตอบ','<div class="form-row"><label>สุ่มจาก<select id="random-kind"><option value="pupil">รายชื่อ / เลขที่ที่มาเรียน</option><option value="team">รายกลุ่ม</option></select></label><label>รูปแบบ<select id="random-repeat"><option value="no">ไม่ซ้ำในรอบนี้</option><option value="yes">สุ่มซ้ำได้</option></select></label></div><div class="random-result" id="random-result" aria-live="polite">พร้อมสุ่ม</div><p id="random-info" class="dialog-help">ใช้เฉพาะรายชื่อที่ติ๊กมาเรียน · เริ่มรอบใหม่ได้เมื่อครบทุกคน</p><div class="random-controls"><button class="primary" data-action="pick-random">สุ่มผู้ตอบ 🎲</button><button class="secondary" data-action="reset-random">เริ่มรอบใหม่</button></div><div class="dialog-actions"><button class="text-button" data-action="classroom">จัดรายชื่อ / เลขที่ก่อน →</button><button class="secondary" data-action="close-dialog">ใช้ผู้ตอบนี้</button></div>')}
function pickRandom(){const team=$('#random-kind').value==='team',repeat=$('#random-repeat').value==='yes',options=team?state.teams:state.roster.filter(p=>p.active!==false),available=repeat?options:options.filter(p=>!state.used.includes(p.id));if(!available.length){$('#random-info').textContent=options.length?'ครบทุกคนแล้ว กดเริ่มรอบใหม่':'ยังไม่มีรายชื่อ / กลุ่ม กรุณาจัดห้องเรียนก่อน';return}const chosen=shuffle(available)[0];if(!repeat)state.used.push(chosen.id);state.mode=team?'team':'individual';state.selected=chosen.id;save();$('#random-result').textContent=team?chosen.name:chosen.number+'. '+chosen.name;$('#random-info').textContent=repeat?'สุ่มซ้ำได้':'เหลือ '+(available.length-1)+' คน / กลุ่มในรอบนี้';updateTotals();if(!$('#teach-view').hidden&&!completed)showQuestion()}
function sourcesUI(){modal('ข้อมูลข้อสอบและคลังคำถาม',`<p class="dialog-help">จัดหมวดตามทักษะที่วัด และเก็บปี รูปแบบ เลขข้อ หน้าต้นฉบับ และแหล่งเฉลยไว้ทุกข้อ<br>ปี 2562 อ่านออกเสียงอ้างจากฉบับกรรมการ · ปี 2566 ยังไม่มีเฉลยยืนยัน จึงให้ครูประเมิน</p><div class="status-box">ขณะนี้มี ${catalog.length} ข้อ · ${banks.size} ชุดที่เปิดใช้งานแล้ว</div><label class="import-file">นำเข้าไฟล์คลังข้อสอบ JSON (เลือกหลายไฟล์ได้)<input type="file" id="import-bank" accept=".json,application/json" multiple></label><p class="database-note">ภาพโจทย์ใช้ต้นฉบับเพื่อรักษาความหมาย คลังที่นำเข้าจะเก็บในความจำของแท็บนี้ เมื่อเปิดแท็บใหม่ต้องนำเข้าอีกครั้ง หากยังไม่ได้เผยแพร่บนเว็บไซต์</p>`)}
async function importBanks(input){try{for(const file of input.files){const b=validateBank(JSON.parse(await file.text()));banks.set(b.id,b);const ids=new Set(b.questions.map(q=>q.id));catalog=catalog.filter(q=>!ids.has(q.id));catalog.push(...b.questions.map(({explanation,image,reading,keySource,...q})=>({...q,auto:!!q.answer})))}loadError='';rebuildFilters();renderLibrary();sourcesUI();toast('นำเข้าคลังข้อสอบแล้ว')}catch(e){toast('นำเข้าไม่สำเร็จ: '+e.message)}}
async function connect(){if(!cloud){try{cloud=await import('./cloud.js')}catch{throw Error('เชื่อม Supabase ไม่สำเร็จ ตรวจอินเทอร์เน็ตแล้วลองใหม่')}}return cloud}
async function cloudUI(){try{const c=await connect(),user=await c.profile();if(!user){modal('เข้าสู่ระบบครู','<p class="dialog-help">ใช้บัญชีครูที่ได้รับอนุมัติในระบบ ป.1 เดิม</p><div class="dialog-actions"><button class="primary" data-action="google-login">เข้าสู่ระบบด้วย Google</button></div><form id="login-form"><label class="dialog-help">อีเมล<input name="email" class="form-input" type="email" autocomplete="username" required></label><label class="dialog-help">รหัสผ่าน<input name="password" class="form-input" type="password" autocomplete="current-password" required></label><div class="dialog-actions"><button class="secondary">เข้าสู่ระบบด้วยอีเมล</button></div></form><p id="login-status" class="dialog-help" role="status"></p>');$('#login-form').onsubmit=async e=>{e.preventDefault();try{const v=new FormData(e.target);await c.signin(v.get('email'),v.get('password'));await cloudUI()}catch(err){$('#login-status').textContent=err.message}};return}const rooms=await c.rooms();$('#cloud-label').textContent='บัญชีครูเชื่อมต่อแล้ว';$('.cloud-dot').classList.add('connected');modal('ห้องเรียน RT บน Supabase',`<p class="dialog-help">เลือกห้องเพื่อโหลดรายชื่อ กลุ่ม คะแนน และลายเขียนที่บันทึกไว้</p>${rooms.map(r=>`<div class="team-card"><h3>${esc(r.name)}</h3><small>ปรับปรุง ${new Date(r.updated_at).toLocaleString('th-TH')}</small><div class="dialog-actions"><button class="primary" data-load-room="${r.id}">เปิดห้องนี้</button></div></div>`).join('')||'<p class="dialog-help">ยังไม่มีห้อง RT ที่บันทึกบนบัญชีนี้</p>'}<div class="dialog-actions"><button class="primary" data-action="cloud-save">บันทึกห้องปัจจุบัน</button><button class="secondary" data-action="cloud-logout">ออกจากระบบ</button></div>`)}catch(e){toast(e.message)}}
async function cloudSave(){try{const c=await connect();if(!await c.profile()){await cloudUI();return}cloudRoom=await c.save(state,cloudRoom);$('#cloud-label').textContent='บันทึกบน Supabase แล้ว';$('.cloud-dot').classList.add('connected');toast('บันทึกห้องเรียนบน Supabase แล้ว')}catch(e){toast(e.message)}}
async function loadCloudRoom(id){try{const c=await connect(),r=await c.load(id);if(state.events.length&&!confirm('โหลดห้องนี้แทนข้อมูลบนเครื่องปัจจุบัน? ควรส่งออกสำรองก่อน'))return;state={...r.state,name:r.name};cloudRoom=r;save();closeModal();updateTotals();toast('โหลดห้องเรียนแล้ว');if(!$('#teach-view').hidden&&!completed)await showQuestion()}catch(e){toast(e.message)}}
async function importP1(){try{const c=await connect();if(!await c.profile()){await cloudUI();return}const rooms=await c.p1Rooms();modal('นำเข้ารายชื่อจากห้องเรียน ป.1',rooms.map(r=>`<div class="team-card"><h3>${esc(r.name)}</h3><button class="primary" data-import-p1="${r.id}">ใช้รายชื่อห้องนี้</button></div>`).join('')||'<p class="dialog-help">ยังไม่มีห้องเรียน ป.1 ในบัญชีนี้</p>')}catch(e){toast(e.message)}}
setInterval(()=>{if(ticking){clock+=(performance.now()-lastTick)/1000;lastTick=performance.now()}const s=Math.floor(clock);$('#timer-display').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},250);
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-action]');if(!b)return;try{
if(b.dataset.category){category=category===b.dataset.category?'':b.dataset.category;pageSize=16;renderLibrary();return}
if(b.dataset.question){await start(b.dataset.question);return}
if(b.dataset.tool){setTool(b.dataset.tool);return}
if(b.dataset.choice){choose(b.dataset.choice);return}
if(b.dataset.score!==undefined){score(+b.dataset.score,$('#written-response')?.value||document.querySelector('.choice.selected')?.dataset.choice||'ครูประเมิน');return}
if(b.dataset.tab){classroom(b.dataset.tab);return}
if(b.dataset.selectTeam){state.mode='team';state.selected=b.dataset.selectTeam;save();updateTotals();closeModal();if(!$('#teach-view').hidden&&!completed)await showQuestion();return}
if(b.dataset.adjust){adjust(b.dataset.adjust,+b.dataset.delta);return}
if(b.dataset.loadRoom){await loadCloudRoom(b.dataset.loadRoom);return}
if(b.dataset.importP1){const c=await connect(),p=await c.p1Pupils(b.dataset.importP1);state.roster=p.map(x=>({...x,id:'p1-'+x.id}));state.used=[];state.teams=[];state.mode='class';state.selected=null;save();classroom('roster');updateTotals();return}
const a=b.dataset.action;
if(a==='start')await start();if(a==='home')home();if(a==='classroom')classroom();if(a==='close-dialog')closeModal();if(a==='scoreboard')classroom('scores');if(a==='random')randomPanel();if(a==='pick-random')pickRandom();
if(a==='reset'){category='';for(const id of ['search','year','form','tag'])$('#'+id).value='';$('#auto-only').checked=false;pageSize=16;renderLibrary()}
if(a==='reset-random'){state.used=[];save();$('#random-result').textContent='พร้อมสุ่ม';$('#random-info').textContent='เริ่มรอบใหม่แล้ว'}
if(a==='save-roster')saveRoster();
if(a==='number-roster'){const n=Number(prompt('จำนวนเลขที่ (1–200)','30'));if(!Number.isInteger(n)||n<1||n>200){toast('ระบุจำนวนเต็ม 1–200');return}$('#roster-editor').value=Array.from({length:n},(_,i)=>(i+1)+' เลขที่ '+(i+1)).join('\n');saveRoster()}
if(a==='divide-teams')divide();
if(a==='move-pupil'){const id=$('#move-pupil').value,target=$('#move-team').value;if(!id||!target){toast('เลือกสมาชิกและกลุ่มก่อน');return}state.teams.forEach(t=>t.members=t.members.filter(v=>v!==id));state.teams.find(t=>t.id===target).members.push(id);save();classroom('teams')}
if(a==='undo-score')undoScore();if(a==='export-csv')exportCSV();
if(a==='export-backup')download('RT-ห้องเรียน.json',JSON.stringify({version:1,state},null,2));
if(a==='rename-room'){const name=$('#room-name').value.trim();if(name){state.name=name;save();classroom('backup')}}
if(a==='undo-ink')undoInk();if(a==='redo-ink')redoInk();
if(a==='clear-ink'){rememberInk();state.ink[activeInkId]=[];paint();save()}
if(a==='timer'){ticking=!ticking;lastTick=performance.now();b.textContent=ticking?'Ⅱ':'▶'}
if(a==='timer-reset'){clock=0;ticking=false;document.querySelector('[data-action=timer]').textContent='▶'}
if(a==='fullscreen'){if(document.fullscreenElement)await document.exitFullscreen();else{document.body.classList.add('projection');await document.documentElement.requestFullscreen().catch(()=>toast('เบราว์เซอร์ไม่รองรับเต็มจอ ยังใช้โหมดจอใหญ่ได้'))}}
if(a==='sources')sourcesUI();if(a==='cloud')await cloudUI();if(a==='cloud-save')await cloudSave();
if(a==='google-login'){const c=await connect();await c.google()}
if(a==='cloud-logout'){const c=await connect();await c.signout();cloudRoom=null;$('#cloud-label').textContent='บันทึกบนเครื่องนี้';$('.cloud-dot').classList.remove('connected');closeModal()}
if(a==='import-p1')await importP1()
}catch(err){toast(err.message)}});
document.addEventListener('change',async e=>{const t=e.target;try{
if(['year','form','tag','auto-only'].includes(t.id)){pageSize=16;renderLibrary()}
if(t.dataset.attendance){state.roster.find(p=>p.id===t.dataset.attendance).active=t.checked;state.used=[];save();updateTotals()}
if(t.id==='recipient-mode'){state.mode=t.value;state.selected=null;recipientOptions();save();updateTotals();if(!$('#teach-view').hidden&&!completed)await showQuestion()}
if(t.id==='recipient-select'){state.selected=t.value||null;save();updateTotals();if(!$('#teach-view').hidden&&!completed)await showQuestion()}
if(t.dataset.teamName){const name=t.value.trim();if(name)state.teams.find(x=>x.id===t.dataset.teamName).name=name;save();updateTotals()}
if(t.id==='import-bank')await importBanks(t);
if(t.id==='import-backup'){const j=JSON.parse(await t.files[0].text());if(j.version!==1||!Array.isArray(j.state?.roster)||!Array.isArray(j.state?.events)||!j.state.ink)throw Error('ไฟล์สำรองไม่ถูกต้อง');if(confirm('แทนข้อมูลห้องปัจจุบันด้วยไฟล์สำรองนี้?')){state=j.state;state.teams||=[];state.used||=[];cloudRoom=null;save();classroom('backup');updateTotals()}}
}catch(err){toast(err.message)}});
$('#search').addEventListener('input',()=>{pageSize=16;renderLibrary()});$('#load-more').onclick=()=>{pageSize+=16;renderLibrary()};$('#previous').onclick=previous;$('#next').onclick=next;$('#reveal').onclick=()=>{if(current()){$('#solution').hidden=false;$('#solution').open=true;$('#solution').scrollIntoView({behavior:'smooth',block:'nearest'})}};
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('projection')});
document.addEventListener('keydown',e=>{if($('#dialog').open||$('#teach-view').hidden||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight'&&!completed)next();if(e.key==='ArrowLeft')previous();if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();e.shiftKey?redoInk():undoInk()}});
window.addEventListener('beforeunload',save);init();
