(()=>{"use strict";
const units=window.P1_BOOK_UNITS||{};
const params=new URLSearchParams(location.search);
let unitNo=Math.min(6,Math.max(1,Number(params.get("unit"))||1));
let unit=units[unitNo];
if(!unit){location.href="index.html";return}
document.documentElement.style.setProperty("--unit",unit.color);
document.title=`หน่วยที่ ${unitNo} ${unit.title} | เพลินภาษา ป.1`;
const $=s=>document.querySelector(s);
const stage=$("#activityStage");
const stepNames=["หน้าบท","รู้จักคำ","ฝึกอ่านคำ","บทฝึกอ่าน","ทบทวน","เกม"];
const stepHelp=[
 "ดูภาพเปิดบทแบบคู่ 2 หน้าจากหนังสือต้นฉบับ แล้วเตรียมตัวเริ่มเรียน",
 "สังเกตภาพและคำ “รู้จักคำ นำเรื่อง” จากต้นฉบับ กดคำด้านข้างเพื่อฟัง",
 "ฝึกอ่านคำทีละคำ ฟังเสียง แล้วอ่านตามให้ชัด",
 "อ่านจากข้อความถอดตามหนังสือแบบคาราโอเกะ พร้อมดูภาพประกอบต้นฉบับทีละหน้า",
 "ตอบคำถามสั้น ๆ เพื่อทบทวนความเข้าใจ",
 "ทำภารกิจสะสมดาวและปลดล็อกเหรียญนักอ่าน"
];
let soundOn=true,step=Number(sessionStorage.getItem(`p1-book-step-${unitNo}`)||0),stars=Number(localStorage.getItem(`p1-book-stars-${unitNo}`)||0);
let wordIndex=0,readingIndex=0,quizIndex=0,quizScore=0,gameIndex=0,gameScore=0;
const completed=new Set(JSON.parse(localStorage.getItem(`p1-book-done-${unitNo}`)||"[]"));

let speakingEl=null,speechSeq=0,karaokeRun=0;
function pictureMarkup(word,cls=""){const idx=unit.pictures?.[word];if(idx===undefined)return "";const x=(idx%3)*50,y=Math.floor(idx/3)*50;return `<span class="word-picture ${cls}" role="img" aria-label="ภาพประกอบคำ ${word}" style="background-image:url('book/word-img/unit${unitNo}-words.webp');background-position:${x}% ${y}%"></span>`}
function clearSpeechVisual(){if(speakingEl){speakingEl.classList.remove("speaking-now");speakingEl=null}}
function stopSpeech(){karaokeRun++;speechSeq++;window.speechSynthesis?.cancel?.();clearSpeechVisual()}
function speak(text,target=null){if(!soundOn||!("speechSynthesis" in window)){clearSpeechVisual();return Promise.resolve()}const token=++speechSeq;clearSpeechVisual();window.speechSynthesis.cancel();if(target){speakingEl=target;target.classList.add("speaking-now")}return new Promise(resolve=>{const u=new SpeechSynthesisUtterance(text);u.lang="th-TH";u.rate=.78;u.pitch=1.04;const done=()=>{if(token===speechSeq)clearSpeechVisual();resolve()};u.onend=done;u.onerror=done;window.speechSynthesis.speak(u)})}
function speechToken(token){const map={"เ-":"เอ","แ-":"แอ","โ-":"โอ","ไ-":"ไอ","ใ-":"ใอ","_ือ":"อือ","เ-ีย":"เอีย","-ัว":"อัว","+":""};return map[token]??token.replace(/[“”"]/g,"")}
function karaokeLineMarkup(line,lineIndex){const tokens=line.trim().split(/\s+/).filter(Boolean);return `<button type="button" class="karaoke-line" data-k-line="${lineIndex}" aria-label="ฟังบรรทัด ${lineIndex+1}">${tokens.map((t,i)=>`<span class="karaoke-token" data-k-token="${i}" data-speech="${speechToken(t).replace(/"/g,"&quot;")}">${t}</span>`).join(" ")}<span class="line-speaker" aria-hidden="true">🔊</span></button>`}
function beginKaraoke(){karaokeRun++;window.speechSynthesis?.cancel?.();clearSpeechVisual();return karaokeRun}
async function readKaraokeLine(lineEl,runId=null){if(!lineEl)return;const run=runId??beginKaraoke();const tokens=[...lineEl.querySelectorAll("[data-k-token]")];lineEl.classList.add("line-reading");for(const el of tokens){if(karaokeRun!==run||step!==3||!document.body.contains(el))break;const txt=el.dataset.speech||"";if(!txt)continue;await speak(txt,el)}lineEl.classList.remove("line-reading")}
async function readKaraokePage(){const run=beginKaraoke();const lines=[...stage.querySelectorAll("[data-k-line]")];const btn=$("#readPageKaraoke");if(btn){btn.disabled=true;btn.textContent="🔊 กำลังอ่าน..."}for(const line of lines){if(karaokeRun!==run||step!==3||!document.body.contains(line))break;await readKaraokeLine(line,run)}if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent="🔊 อ่านทั้งหน้า"}}
function pagePictureWords(page){const text=(page?.lines||[]).join(" ");return unit.words.filter(w=>unit.pictures?.[w]!==undefined&&text.includes(w))}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function save(){localStorage.setItem(`p1-book-stars-${unitNo}`,stars);localStorage.setItem(`p1-book-done-${unitNo}`,JSON.stringify([...completed]));sessionStorage.setItem(`p1-book-step-${unitNo}`,step)}
function addStar(n=1){stars+=n;save();$("#starCount").textContent=`⭐ ${stars}`;for(let i=0;i<n;i++){const s=document.createElement("span");s.className="star-pop";s.textContent="⭐";s.style.left=`${40+Math.random()*20}%`;s.style.top=`${48+Math.random()*8}%`;document.body.append(s);setTimeout(()=>s.remove(),950)}}
function crop(segment,cls=""){const pct=(segment.y/unit.sprite.h)*100;return `<div class="book-crop ${cls}" style="aspect-ratio:${unit.sprite.w}/${segment.h}"><img src="${unit.asset}" alt="ภาพจากหนังสือภาษาพาที หน่วยที่ ${unitNo}" style="--page-y:${pct}%;" loading="eager"></div>`}
function zoomButton(segment,label="ขยายภาพ"){return `<button class="secondary-action" type="button" data-zoom="${unit.segments.indexOf(segment)}">🔎 ${label}</button>`}
function spread(indices=[0,1],cls=""){return `<div class="stitched-cover ${cls}"><img src="book/unit${unitNo}-cover.webp" alt="ภาพเปิดบทแบบคู่ 2 หน้า หน่วยที่ ${unitNo}" loading="eager"></div>`}
function spreadZoomButton(indices=[0,1],label="ขยายภาพคู่ 2 หน้า"){return `<button class="secondary-action" type="button" data-zoom-spread="${indices.join(",")}">🔎 ${label}</button>`}
function sourceNote(){return '<span class="source-note">📘 ภาพจากหนังสือภาษาพาทีต้นฉบับ</span>'}
function setHead(){$("#unitKicker").textContent=`หน่วยที่ ${unitNo} · ภาษาพาที`;$("#unitTitle").textContent=unit.title;$("#unitLead").textContent=unit.lead;$("#activityKicker").textContent=`กิจกรรมที่ ${step+1}`;$("#activityTitle").textContent=stepNames[step];$("#activityHelp").textContent=stepHelp[step];$("#stepCount").textContent=`${step+1} / 6`;$("#starCount").textContent=`⭐ ${stars}`;$("#progressBar").style.width=`${((step+1)/6)*100}%`;$("#prevStep").disabled=step===0;$("#nextStep").textContent=step===5?"กลับสารบัญ ✓":"ถัดไป ›"}
function renderNav(){const nav=$("#stepNav");nav.innerHTML=stepNames.map((n,i)=>`<button type="button" data-step="${i}" class="${i===step?"active":""} ${completed.has(i)?"done":""}"><span>${completed.has(i)?"✓":i+1}</span><small>${n}</small></button>`).join("");nav.querySelectorAll("button").forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);render()})}
function markDone(){completed.add(step);save();renderNav()}

function renderCover(){stage.innerHTML=`<div class="center-stage">${sourceNote()}<div class="spread-heading"><strong>ภาพเปิดบทแบบคู่ 2 หน้า</strong><span>หน้าซ้ายและหน้าขวาจากหนังสือต้นฉบับ</span></div>${spread([0,1],"cover-spread")}<div class="word-controls">${spreadZoomButton([0,1])}<button class="big-action" id="coverStart">เริ่มเรียนหน่วยนี้ →</button></div></div>`;$("#coverStart").onclick=()=>{markDone();step=1;render()}}
function renderVocab(){stage.innerHTML=`<div class="activity-grid"><div><div class="center-stage">${sourceNote()}${crop(unit.segments[2],"reading")}${zoomButton(unit.segments[2],"ขยายหน้าคำศัพท์")}</div></div><div class="instruction-card"><span class="kicker">คำในบทนี้</span><h3>กดคำเพื่อฟัง แล้วอ่านตาม</h3><p>คำที่มีภาพในหนังสือจะแสดงภาพประกอบจากต้นฉบับ</p><div class="word-list">${unit.words.map((w,i)=>`<button class="word-chip ${unit.pictures?.[w]!==undefined?"has-picture":""}" data-word="${i}">${pictureMarkup(w,"chip-picture")}<span>${w}</span></button>`).join("")}</div><div class="word-controls"><button class="big-action" id="readAllWords">🔊 ฟังคำทั้งหมด</button></div></div></div>`;const chips=[...stage.querySelectorAll("[data-word]")];chips.forEach(b=>b.onclick=()=>{chips.forEach(x=>x.classList.remove("active"));b.classList.add("active");speak(unit.words[Number(b.dataset.word)],b)});$("#readAllWords").onclick=async e=>{const btn=e.currentTarget,old=btn.textContent;btn.disabled=true;btn.textContent="🔊 กำลังอ่าน...";for(const b of chips){if(step!==1||!document.body.contains(b))break;chips.forEach(x=>x.classList.remove("active"));b.classList.add("active");await speak(unit.words[Number(b.dataset.word)],b)}if(document.body.contains(btn)){btn.disabled=false;btn.textContent=old}}}
function renderWordPractice(){const w=unit.words[wordIndex];stage.innerHTML=`<div class="word-practice"><div class="word-stage"><span class="word-number">คำที่ ${wordIndex+1} จาก ${unit.words.length}</span><div class="practice-visual">${pictureMarkup(w,"practice-picture")}</div><strong id="practiceWord">${w}</strong><p>ฟัง → อ่านตาม → กด “อ่านได้แล้ว”</p><div class="word-controls"><button class="secondary-action" id="speakWord">🔊 ฟังคำ</button><button class="big-action" id="wordDone">✓ อ่านได้แล้ว</button></div></div><div class="instruction-card">${sourceNote()}<h3>มองหาคำในภาพต้นฉบับ</h3><p>ถ้าคำนี้มีภาพประกอบ ระบบจะแสดงภาพจากหน้ารู้จักคำ นำเรื่องให้ด้วย</p><div style="margin-top:14px">${crop(unit.segments[2],"compact")}</div></div></div>`;$("#speakWord").onclick=()=>speak(w,$("#practiceWord"));$("#wordDone").onclick=()=>{addStar(1);wordIndex++;if(wordIndex>=unit.words.length){wordIndex=0;markDone();stage.innerHTML=`<div class="completion"><div><div class="medal">🌟</div><h3>อ่านครบทุกคำแล้ว</h3><p>เก่งมาก ได้ฝึกคำสำคัญครบ ${unit.words.length} คำ</p><button class="big-action" id="goReading">ไปบทฝึกอ่าน →</button></div></div>`;$("#goReading").onclick=()=>{step=3;render()}}else renderWordPractice()}}
function renderReading(){stopSpeech();const seg=unit.segments[3+readingIndex],page=unit.readingPages?.[readingIndex]||{title:"บทฝึกอ่าน",kind:"บทฝึกอ่าน",bookPage:`หน้า ${readingIndex+1}`,lines:[]},picWords=pagePictureWords(page);stage.innerHTML=`<div class="reading-karaoke-layout"><section class="reading-original"><div class="reading-source-head">${sourceNote()}<span>${page.bookPage}</span></div>${crop(seg,"reading")}<div class="word-controls">${zoomButton(seg,"ขยายหน้าต้นฉบับ")}</div><p class="original-caption">ภาพและการจัดวางจากหนังสือต้นฉบับ</p></section><section class="karaoke-reader"><div class="karaoke-head"><div><span class="kicker">${page.kind}</span><h3>${page.title}</h3><p>กด “อ่านทั้งหน้า” หรือแตะบรรทัดเพื่อฟังทีละบรรทัด คำที่กำลังอ่านจะขยายและเปลี่ยนสี</p></div><span class="book-page-chip">${page.bookPage}</span></div><div class="reading-page-buttons">${unit.readingPages.map((p,i)=>`<button data-reading="${i}" class="${i===readingIndex?"active":""}">หน้า ${i+1}<small>${p.bookPage}</small></button>`).join("")}</div><div class="karaoke-controls"><button class="big-action" id="readPageKaraoke">🔊 อ่านทั้งหน้า</button><button class="secondary-action" id="stopKaraoke">⏹ หยุด</button><button class="secondary-action" id="restartKaraoke">↻ อ่านใหม่</button></div><div class="karaoke-text" aria-label="บทอ่านคาราโอเกะ">${page.lines.map((line,i)=>karaokeLineMarkup(line,i)).join("")}</div>${picWords.length?`<div class="reading-picture-strip"><strong>ภาพประกอบคำจากต้นฉบับ</strong><div>${picWords.map(w=>`<button type="button" class="reading-picture-word" data-picture-word="${w}">${pictureMarkup(w,"reading-picture-thumb")}<span>${w}</span></button>`).join("")}</div></div>`:""}<div class="reading-tips"><strong>ฝึกอ่านแบบคาราโอเกะ</strong><br>อ่านตามคำที่ขยายและเปลี่ยนสีทีละคำ แล้วลองอ่านเองอีกรอบโดยไม่กดเสียง<br><br><strong>สาระภาษา:</strong><br>${unit.focus}</div></section></div>`;stage.querySelectorAll("[data-reading]").forEach(b=>b.onclick=()=>{readingIndex=Number(b.dataset.reading);renderReading()});stage.querySelectorAll("[data-k-line]").forEach(line=>line.onclick=()=>readKaraokeLine(line));stage.querySelectorAll("[data-picture-word]").forEach(b=>b.onclick=()=>speak(b.dataset.pictureWord,b));$("#readPageKaraoke").onclick=readKaraokePage;$("#stopKaraoke").onclick=stopSpeech;$("#restartKaraoke").onclick=()=>{stopSpeech();setTimeout(readKaraokePage,80)}}
function renderQuiz(){if(quizIndex>=unit.review.length){markDone();stage.innerHTML=`<div class="completion"><div><div class="medal">🏅</div><h3>ทบทวนจบแล้ว</h3><p>ตอบถูก ${quizScore} จาก ${unit.review.length} ข้อ</p><button class="big-action" id="toGame">ไปเกมสะสมดาว →</button></div></div>`;$("#toGame").onclick=()=>{step=5;render()};return}const q=unit.review[quizIndex];stage.innerHTML=`<div class="quiz"><div class="quiz-box"><div class="quiz-meta"><span>ข้อ ${quizIndex+1} / ${unit.review.length}</span><span>คะแนน ${quizScore}</span></div><h3>${q.q}</h3><div class="quiz-options">${shuffle(q.o).map(o=>`<button class="quiz-option ${unit.pictures?.[o]!==undefined?"has-picture":""}" data-answer="${o.replace(/"/g,"&quot;")}">${pictureMarkup(o,"option-picture")}<span>${o}</span></button>`).join("")}</div><p id="quizFeedback" class="feedback"></p></div><div class="instruction-card"><strong>ทบทวนจากภาพต้นฉบับ</strong><p>คำที่มีภาพประกอบจะแสดงภาพจากหนังสือเพื่อช่วยเชื่อมโยงความหมาย</p><div style="margin-top:13px">${crop(unit.segments[2],"compact")}</div></div></div>`;stage.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{const buttons=[...stage.querySelectorAll("[data-answer]")],ok=b.dataset.answer===q.a;buttons.forEach(x=>x.disabled=true);b.classList.add(ok?"correct":"wrong");const correct=buttons.find(x=>x.dataset.answer===q.a);if(!ok&&correct)correct.classList.add("correct");const fb=$("#quizFeedback");fb.textContent=ok?"✓ ถูกต้อง เก่งมาก!":`คำตอบที่ถูกคือ “${q.a}”`;fb.className=`feedback ${ok?"good":"bad"}`;if(ok){quizScore++;addStar(1)}speak(q.a,ok?b:correct).then(()=>setTimeout(()=>{quizIndex++;renderQuiz()},220))})}
function gameQuestion(){const qs=unit.review;if(gameIndex>=qs.length){completed.add(5);save();const perfect=gameScore===qs.length;if(perfect)addStar(2);stage.innerHTML=`<div class="completion"><div><div class="medal">${perfect?"🏆":"🎖️"}</div><h3>${perfect?"นักอ่านดาวทอง!":"ผ่านด่านแล้ว!"}</h3><p>ภารกิจเกม ${gameScore}/${qs.length} · ดาวสะสมทั้งหมด ${stars}</p><div class="unit-links"><button class="big-action" id="playAgain">เล่นเกมอีกครั้ง</button><a class="secondary-action" href="index.html">กลับสารบัญ</a>${unitNo<6?`<a class="secondary-action" href="lesson.html?unit=${unitNo+1}">ไปหน่วยถัดไป →</a>`:""}</div></div></div>`;$("#playAgain").onclick=()=>{gameIndex=0;gameScore=0;renderGame()};renderNav();return}const q=qs[gameIndex];stage.innerHTML=`<div class="game-shell"><div class="reward-card"><div class="trophy">⭐</div><h3>ภารกิจนักอ่าน</h3><div class="xp">${stars} ดาว</div><p>ตอบให้ถูกเพื่อสะสมดาว<br>ครบทุกข้อรับเหรียญผ่านด่าน</p><div class="book-mini">${crop(unit.segments[2],"compact")}</div></div><div class="mission"><span class="kicker">ภารกิจ ${gameIndex+1} / ${qs.length}</span><h3>${q.q}</h3><div class="mission-options">${shuffle(q.o).map(o=>`<button class="${unit.pictures?.[o]!==undefined?"has-picture":""}" data-game-answer="${o.replace(/"/g,"&quot;")}">${pictureMarkup(o,"option-picture")}<span>${o}</span></button>`).join("")}</div><p id="gameFeedback" class="feedback"></p></div></div>`;stage.querySelectorAll("[data-game-answer]").forEach(b=>b.onclick=()=>{const buttons=[...stage.querySelectorAll("[data-game-answer]")],ok=b.dataset.gameAnswer===q.a;buttons.forEach(x=>x.disabled=true);b.classList.add(ok?"correct":"wrong");const correct=buttons.find(x=>x.dataset.gameAnswer===q.a);if(!ok&&correct)correct.classList.add("correct");const fb=$("#gameFeedback");fb.textContent=ok?"⭐ ได้ดาว!":`คำตอบคือ “${q.a}”`;fb.className=`feedback ${ok?"good":"bad"}`;if(ok){gameScore++;addStar(1)}speak(q.a,ok?b:correct).then(()=>setTimeout(()=>{gameIndex++;gameQuestion()},220))})}
function renderGame(){gameQuestion()}
function zoomSegment(index){const seg=unit.segments[index];$("#zoomContent").innerHTML=crop(seg,"reading");$("#zoomDialog").showModal()}
function zoomSpread(indices){$("#zoomContent").innerHTML=spread(indices,"zoom-spread");$("#zoomDialog").showModal()}
function bindZoom(){stage.querySelectorAll("[data-zoom]").forEach(b=>b.onclick=()=>zoomSegment(Number(b.dataset.zoom)));stage.querySelectorAll("[data-zoom-spread]").forEach(b=>b.onclick=()=>zoomSpread(b.dataset.zoomSpread.split(",").map(Number)))}
function resetStep(){stopSpeech();if(step===2)wordIndex=0;if(step===3)readingIndex=0;if(step===4){quizIndex=0;quizScore=0}if(step===5){gameIndex=0;gameScore=0}render()}
function render(){stopSpeech();step=Math.max(0,Math.min(5,step));save();setHead();renderNav();if(step===0)renderCover();if(step===1)renderVocab();if(step===2)renderWordPractice();if(step===3)renderReading();if(step===4)renderQuiz();if(step===5)renderGame();bindZoom();window.scrollTo({top:0,behavior:"smooth"})}
$("#prevStep").onclick=()=>{if(step>0){step--;render()}};
$("#nextStep").onclick=()=>{markDone();if(step<5){step++;render()}else location.href="index.html"};
$("#restartStep").onclick=resetStep;
$("#soundToggle").onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?"🔊":"🔇";e.currentTarget.setAttribute("aria-pressed",String(soundOn));if(!soundOn)stopSpeech()};
$("#closeZoom").onclick=()=>$("#zoomDialog").close();
$("#zoomDialog").addEventListener("click",e=>{if(e.target===$("#zoomDialog"))$("#zoomDialog").close()});
$("#unitHero").style.setProperty("--unit",unit.color);
$("#heroBookImage").innerHTML=spread([0,1],"hero-spread");
render();
})();