(()=>{"use strict";
const units=window.P1_BOOK_UNITS||{};
const params=new URLSearchParams(location.search);
let unitNo=Math.min(6,Math.max(1,Number(params.get("unit"))||1));
let unit=units[unitNo];
if(!unit){location.href="index.html";return}
document.documentElement.style.setProperty("--unit",unit.color);
document.title=`หน่วยที่ ${unitNo} ${unit.title} | เพลินภาษา ป.1`;
const $=s=>document.querySelector(s);
const stage=$("#activityStage");
const stepNames=["หน้าบท","รู้จักคำ","ฝึกอ่านคำ","บทฝึกอ่าน","ทบทวน","เกม"];
const stepHelp=[
 "ดูภาพเปิดบทแบบคู่ 2 หน้าจากหนังสือต้นฉบับ แล้วเตรียมตัวเริ่มเรียน",
 "สังเกตภาพและคำ “รู้จักคำ นำเรื่อง” จากต้นฉบับ กดคำด้านข้างเพื่อฟัง",
 "ฝึกอ่านคำทีละคำ ฟังเสียง แล้วอ่านตามให้ชัด",
 "อ่านบทเรียนจากหน้าหนังสือต้นฉบับทีละหน้า",
 "ตอบคำถามสั้น ๆ เพื่อทบทวนความเข้าใจ",
 "ทำภารกิจสะสมดาวและปลดล็อกเหรียญนักอ่าน"
];
let soundOn=true,step=Number(sessionStorage.getItem(`p1-book-step-${unitNo}`)||0),stars=Number(localStorage.getItem(`p1-book-stars-${unitNo}`)||0);
let wordIndex=0,readingIndex=0,quizIndex=0,quizScore=0,gameIndex=0,gameScore=0;
const completed=new Set(JSON.parse(localStorage.getItem(`p1-book-done-${unitNo}`)||"[]"));

function speak(text){if(!soundOn||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="th-TH";u.rate=.78;u.pitch=1.04;speechSynthesis.speak(u)}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function save(){localStorage.setItem(`p1-book-stars-${unitNo}`,stars);localStorage.setItem(`p1-book-done-${unitNo}`,JSON.stringify([...completed]));sessionStorage.setItem(`p1-book-step-${unitNo}`,step)}
function addStar(n=1){stars+=n;save();$("#starCount").textContent=`⭐ ${stars}`;for(let i=0;i<n;i++){const s=document.createElement("span");s.className="star-pop";s.textContent="⭐";s.style.left=`${40+Math.random()*20}%`;s.style.top=`${48+Math.random()*8}%`;document.body.append(s);setTimeout(()=>s.remove(),950)}}
function crop(segment,cls=""){const pct=(segment.y/unit.sprite.h)*100;return `<div class="book-crop ${cls}" style="aspect-ratio:${unit.sprite.w}/${segment.h}"><img src="${unit.asset}" alt="ภาพจากหนังสือภาษาพาที หน่วยที่ ${unitNo}" style="transform:translateY(-${pct}%);" loading="eager"></div>`}
function zoomButton(segment,label="ขยายภาพ"){return `<button class="secondary-action" type="button" data-zoom="${unit.segments.indexOf(segment)}">🔎 ${label}</button>`}
function spread(indices=[0,1],cls=""){return `<div class="book-spread ${cls}">${indices.map(i=>crop(unit.segments[i],"spread-page")).join("")}</div>`}
function spreadZoomButton(indices=[0,1],label="ขยายภาพคู่ 2 หน้า"){return `<button class="secondary-action" type="button" data-zoom-spread="${indices.join(",")}">🔎 ${label}</button>`}
function sourceNote(){return '<span class="source-note">📘 ภาพจากหนังสือภาษาพาทีต้นฉบับ</span>'}
function setHead(){$("#unitKicker").textContent=`หน่วยที่ ${unitNo} · ภาษาพาที`;$("#unitTitle").textContent=unit.title;$("#unitLead").textContent=unit.lead;$("#activityKicker").textContent=`กิจกรรมที่ ${step+1}`;$("#activityTitle").textContent=stepNames[step];$("#activityHelp").textContent=stepHelp[step];$("#stepCount").textContent=`${step+1} / 6`;$("#starCount").textContent=`⭐ ${stars}`;$("#progressBar").style.width=`${((step+1)/6)*100}%`;$("#prevStep").disabled=step===0;$("#nextStep").textContent=step===5?"กลับสารบัญ ✓":"ถัดไป ›"}
function renderNav(){const nav=$("#stepNav");nav.innerHTML=stepNames.map((n,i)=>`<button type="button" data-step="${i}" class="${i===step?"active":""} ${completed.has(i)?"done":""}"><span>${completed.has(i)?"✓":i+1}</span><small>${n}</small></button>`).join("");nav.querySelectorAll("button").forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);render()})}
function markDone(){completed.add(step);save();renderNav()}

function renderCover(){stage.innerHTML=`<div class="center-stage">${sourceNote()}<div class="spread-heading"><strong>ภาพเปิดบทแบบคู่ 2 หน้า</strong><span>หน้าซ้ายและหน้าขวาจากหนังสือต้นฉบับ</span></div>${spread([0,1],"cover-spread")}<div class="word-controls">${spreadZoomButton([0,1])}<button class="big-action" id="coverStart">เริ่มเรียนหน่วยนี้ →</button></div></div>`;$("#coverStart").onclick=()=>{markDone();step=1;render()}}
function renderVocab(){stage.innerHTML=`<div class="activity-grid"><div><div class="center-stage">${sourceNote()}${crop(unit.segments[2],"reading")}${zoomButton(unit.segments[2],"ขยายหน้าคำศัพท์")}</div></div><div class="instruction-card"><span class="kicker">คำในบทนี้</span><h3>กดคำเพื่อฟัง แล้วอ่านตาม</h3><p>คำและภาพอ้างอิงจากหน้ารู้จักคำ นำเรื่องของหนังสือต้นฉบับ</p><div class="word-list">${unit.words.map((w,i)=>`<button class="word-chip" data-word="${i}">${w}</button>`).join("")}</div><div class="word-controls"><button class="big-action" id="readAllWords">🔊 ฟังคำทั้งหมด</button></div></div></div>`;stage.querySelectorAll("[data-word]").forEach(b=>b.onclick=()=>{stage.querySelectorAll("[data-word]").forEach(x=>x.classList.remove("active"));b.classList.add("active");speak(unit.words[Number(b.dataset.word)])});$("#readAllWords").onclick=async()=>{for(const w of unit.words){speak(w);await new Promise(r=>setTimeout(r,1150))}}}
function renderWordPractice(){const w=unit.words[wordIndex];stage.innerHTML=`<div class="word-practice"><div class="word-stage"><span class="word-number">คำที่ ${wordIndex+1} จาก ${unit.words.length}</span><strong>${w}</strong><p>ฟัง → อ่านตาม → กด “อ่านได้แล้ว”</p><div class="word-controls"><button class="secondary-action" id="speakWord">🔊 ฟังคำ</button><button class="big-action" id="wordDone">✓ อ่านได้แล้ว</button></div></div><div class="instruction-card">${sourceNote()}<h3>มองหาคำในภาพต้นฉบับ</h3><p>ใช้ภาพ “รู้จักคำ นำเรื่อง” เป็นตัวช่วยเชื่อมภาพกับคำ ก่อนอ่านคำด้วยตนเอง</p><div style="margin-top:14px">${crop(unit.segments[2],"compact")}</div></div></div>`;$("#speakWord").onclick=()=>speak(w);$("#wordDone").onclick=()=>{addStar(1);wordIndex++;if(wordIndex>=unit.words.length){wordIndex=0;markDone();stage.innerHTML=`<div class="completion"><div><div class="medal">🌟</div><h3>อ่านครบทุกคำแล้ว</h3><p>เก่งมาก ได้ฝึกคำสำคัญครบ ${unit.words.length} คำ</p><button class="big-action" id="goReading">ไปบทฝึกอ่าน →</button></div></div>`;$("#goReading").onclick=()=>{step=3;render()}}else renderWordPractice()}}
function renderReading(){const seg=unit.segments[3+readingIndex];stage.innerHTML=`<div class="reading-panel"><div class="center-stage">${sourceNote()}${crop(seg,"reading")}<div class="word-controls">${zoomButton(seg,"ขยายหน้าบทอ่าน")}<button class="secondary-action" id="listenKeys">🔊 ฟังคำสำคัญ</button></div></div><aside class="reading-side"><span class="kicker">บทฝึกอ่าน</span><h3>อ่านทีละหน้า</h3><div class="reading-page-buttons">${[0,1,2].map(i=>`<button data-reading="${i}" class="${i===readingIndex?"active":""}">หน้าอ่านที่ ${i+1}</button>`).join("")}</div><div class="reading-tips"><strong>วิธีฝึก</strong><br>1. ครูอ่านนำหนึ่งรอบ<br>2. นักเรียนชี้ตามข้อความในภาพ<br>3. อ่านพร้อมกัน<br>4. อ่านเป็นคู่หรือรายบุคคล<br><br><strong>สาระภาษา:</strong><br>${unit.focus}</div></aside></div>`;stage.querySelectorAll("[data-reading]").forEach(b=>b.onclick=()=>{readingIndex=Number(b.dataset.reading);renderReading()});$("#listenKeys").onclick=()=>speak(unit.words.slice(0,Math.min(8,unit.words.length)).join("   "))}
function renderQuiz(){if(quizIndex>=unit.review.length){markDone();stage.innerHTML=`<div class="completion"><div><div class="medal">🏅</div><h3>ทบทวนจบแล้ว</h3><p>ตอบถูก ${quizScore} จาก ${unit.review.length} ข้อ</p><button class="big-action" id="toGame">ไปเกมสะสมดาว →</button></div></div>`;$("#toGame").onclick=()=>{step=5;render()};return}const q=unit.review[quizIndex];stage.innerHTML=`<div class="quiz"><div class="quiz-box"><div class="quiz-meta"><span>ข้อ ${quizIndex+1} / ${unit.review.length}</span><span>คะแนน ${quizScore}</span></div><h3>${q.q}</h3><div class="quiz-options">${shuffle(q.o).map(o=>`<button class="quiz-option" data-answer="${o.replace(/"/g,"&quot;")}">${o}</button>`).join("")}</div><p id="quizFeedback" class="feedback"></p></div><div class="instruction-card"><strong>ทบทวนจากภาพต้นฉบับ</strong><p>ถ้านึกไม่ออก ให้ย้อนดูภาพ “รู้จักคำ นำเรื่อง” แล้วค่อยตอบ</p><div style="margin-top:13px">${crop(unit.segments[2],"compact")}</div></div></div>`;stage.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{const ok=b.dataset.answer===q.a;stage.querySelectorAll("[data-answer]").forEach(x=>x.disabled=true);b.classList.add(ok?"correct":"wrong");const fb=$("#quizFeedback");fb.textContent=ok?"✓ ถูกต้อง เก่งมาก!":`คำตอบที่ถูกคือ “${q.a}”`;fb.className=`feedback ${ok?"good":"bad"}`;if(ok){quizScore++;addStar(1);speak("ถูกต้อง")}else speak(q.a);setTimeout(()=>{quizIndex++;renderQuiz()},900)})}
function gameQuestion(){const qs=unit.review;if(gameIndex>=qs.length){completed.add(5);save();const perfect=gameScore===qs.length;if(perfect)addStar(2);stage.innerHTML=`<div class="completion"><div><div class="medal">${perfect?"🏆":"🎖️"}</div><h3>${perfect?"นักอ่านดาวทอง!":"ผ่านด่านแล้ว!"}</h3><p>ภารกิจเกม ${gameScore}/${qs.length} · ดาวสะสมทั้งหมด ${stars}</p><div class="unit-links"><button class="big-action" id="playAgain">เล่นเกมอีกครั้ง</button><a class="secondary-action" href="index.html">กลับสารบัญ</a>${unitNo<6?`<a class="secondary-action" href="lesson.html?unit=${unitNo+1}">ไปหน่วยถัดไป →</a>`:""}</div></div></div>`;$("#playAgain").onclick=()=>{gameIndex=0;gameScore=0;renderGame()};renderNav();return}const q=qs[gameIndex];stage.innerHTML=`<div class="game-shell"><div class="reward-card"><div class="trophy">⭐</div><h3>ภารกิจนักอ่าน</h3><div class="xp">${stars} ดาว</div><p>ตอบให้ถูกเพื่อสะสมดาว<br>ครบทุกข้อรับเหรียญผ่านด่าน</p><div class="book-mini">${crop(unit.segments[2],"compact")}</div></div><div class="mission"><span class="kicker">ภารกิจ ${gameIndex+1} / ${qs.length}</span><h3>${q.q}</h3><div class="mission-options">${shuffle(q.o).map(o=>`<button data-game-answer="${o.replace(/"/g,"&quot;")}">${o}</button>`).join("")}</div><p id="gameFeedback" class="feedback"></p></div></div>`;stage.querySelectorAll("[data-game-answer]").forEach(b=>b.onclick=()=>{const ok=b.dataset.gameAnswer===q.a;stage.querySelectorAll("[data-game-answer]").forEach(x=>x.disabled=true);b.classList.add(ok?"correct":"wrong");const fb=$("#gameFeedback");fb.textContent=ok?"⭐ ได้ดาว!":"ลองจำคำนี้ไว้ แล้วไปข้อต่อไป";fb.className=`feedback ${ok?"good":"bad"}`;if(ok){gameScore++;addStar(1);speak("เก่งมาก ได้ดาว")}else speak(q.a);setTimeout(()=>{gameIndex++;gameQuestion()},850)})}
function renderGame(){gameQuestion()}
function zoomSegment(index){const seg=unit.segments[index];$("#zoomContent").innerHTML=crop(seg,"reading");$("#zoomDialog").showModal()}
function zoomSpread(indices){$("#zoomContent").innerHTML=spread(indices,"zoom-spread");$("#zoomDialog").showModal()}
function bindZoom(){stage.querySelectorAll("[data-zoom]").forEach(b=>b.onclick=()=>zoomSegment(Number(b.dataset.zoom)));stage.querySelectorAll("[data-zoom-spread]").forEach(b=>b.onclick=()=>zoomSpread(b.dataset.zoomSpread.split(",").map(Number)))}
function resetStep(){window.speechSynthesis?.cancel?.();if(step===2)wordIndex=0;if(step===3)readingIndex=0;if(step===4){quizIndex=0;quizScore=0}if(step===5){gameIndex=0;gameScore=0}render()}
function render(){step=Math.max(0,Math.min(5,step));save();setHead();renderNav();if(step===0)renderCover();if(step===1)renderVocab();if(step===2)renderWordPractice();if(step===3)renderReading();if(step===4)renderQuiz();if(step===5)renderGame();bindZoom();window.scrollTo({top:0,behavior:"smooth"})}
$("#prevStep").onclick=()=>{if(step>0){step--;render()}};
$("#nextStep").onclick=()=>{markDone();if(step<5){step++;render()}else location.href="index.html"};
$("#restartStep").onclick=resetStep;
$("#soundToggle").onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?"🔊":"🔇";e.currentTarget.setAttribute("aria-pressed",String(soundOn));if(!soundOn)window.speechSynthesis?.cancel?.()};
$("#closeZoom").onclick=()=>$("#zoomDialog").close();
$("#zoomDialog").addEventListener("click",e=>{if(e.target===$("#zoomDialog"))$("#zoomDialog").close()});
$("#unitHero").style.setProperty("--unit",unit.color);
$("#heroBookImage").innerHTML=spread([0,1],"hero-spread");
render();
})();