import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.110.8/+esm';
const db=createClient('https://xnpzkhjodokvcgzovlxx.supabase.co','sb_publishable_r0M5jKyJcrQAKstRlmYOdQ_J_0aLofN',{auth:{storageKey:'p1-classroom-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const base=new URL('../',import.meta.url), $=(s,e=document)=>e.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const th=n=>String(n).replace(/\d/g,c=>'๐๑๒๓๔๕๖๗๘๙'[c]);
let profile={role:'guest'},session=null,room=null,rooms=[],pupils=[],chosen=null,mode='class',drawMode='',color='#d93243',width=4,strokes=[],undo=[],redo=[],svg,host,key='',activeStroke,deck=[],lastRandom='';
const panel=document.createElement('dialog'); panel.className='p1c-dialog';document.body.append(panel);
const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('classroom.css',base);document.head.append(style);
function status(text){let el=$('.p1c-status',panel);if(el)el.textContent=text}
function open(title,html){panel.innerHTML=`<div class="p1c-head"><h2>${esc(title)}</h2><button data-close aria-label="ปิด">✕</button></div><div class="p1c-status" role="status"></div>${html}`;$('[data-close]',panel).onclick=()=>panel.close();if(!panel.open)panel.showModal()}
function button(label,fn,where){const b=document.createElement('button');b.type='button';b.textContent=label;b.className='p1c-button';b.onclick=()=>Promise.resolve(fn()).catch(e=>{status(e.message);console.error('P1 classroom:',e.message)});where.append(b);return b}
async function rpc(action,args={}){const {data,error}=await db.rpc('p1_classroom',{action,args});if(error)throw error;if(data?.error)throw Error(data.error);return data}
async function anonymous(){const {data,error}=await db.auth.getSession();if(error)throw error;if(data.session)return data.session;const r=await db.auth.signInAnonymously();if(r.error)throw r.error;return r.data.session}
async function refresh(){const r=await db.auth.getSession();session=r.data.session;profile=session?await rpc('profile'):{role:'guest'};installMenu();if(profile.role!=='teacher'){drawMode='';svg?.remove();toolbar.hidden=true}document.dispatchEvent(new CustomEvent('p1-classroom-ready',{detail:{role:profile.role}}))}
async function google(){if(session?.user?.is_anonymous){await rpc('leave');await db.auth.signOut()}const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:new URL('index.html',base).href}});if(error)throw error}
async function signout(){drawMode='';svg?.remove();toolbar.hidden=true;await db.auth.signOut();profile={role:'guest'};room=null;pupils=[];chosen=null;sessionStorage.removeItem('p1-class-selection');panel.close();installMenu();document.dispatchEvent(new Event('p1-trace-context'))}
function home(){open('ห้องเรียนของฉัน',`<p>${profile.role==='teacher'?'บัญชีครู':profile.role==='student'?`สวัสดี ${esc(profile.pupil.name)} · ${esc(profile.room.name)}`:'เข้าห้องด้วยลิงก์หรือ QR ที่ครูให้ หรือเลือกเข้าสู่ระบบสำหรับครู'}</p><div class="p1c-actions"></div>`);const a=$('.p1c-actions',panel);
 if(profile.role==='teacher'){button('ห้องเรียนและรายชื่อ',manage,a);button('เครื่องมือเขียน',()=>{panel.close();enableDrawing()},a);button('สุ่มชื่อ / เลขที่',randomPanel,a);button('ผลกิจกรรม',results,a);button('คะแนนฝึกเขียน',traceResults,a);button('เลือกห้องและผู้ตอบ',selectMode,a)}
 else if(profile.role==='student'){button('เปลี่ยนผู้เรียน',async()=>{await rpc('leave');await signout();location.href=new URL('index.html',base)},a)}
 else if(session&&!session.user.is_anonymous){const p=document.createElement('p');p.textContent='บัญชีนี้ยังไม่มีสิทธิ์ครู กรุณาติดต่อผู้ดูแลเพื่ออนุมัติ';a.append(p)}
 else button('ครูเข้าสู่ระบบด้วย Google',google,a);
 if(session)button('ออกจากระบบ',signout,a);
}
function installMenu(){const menu=$('.unit1-menu-list');let b=$('#p1ClassroomMenu');if(!b){b=document.createElement('button');b.id='p1ClassroomMenu';b.type='button';b.className='p1c-button';b.onclick=()=>{ $('.unit1-menu-backdrop')?.classList.remove('open');home()};(menu||$('.welcome-topbar')||$('header')||document.body).append(b)}if(menu&&b.parentElement!==menu)menu.append(b);const label=profile.role==='teacher'?'🧰 เครื่องมือครู':profile.role==='student'?`👤 ${profile.pupil.name}`:'☰ ห้องเรียน / เข้าสู่ระบบ';if(b.dataset.label!==label){b.dataset.label=label;b.textContent=label;}}
async function loadRooms(){const r=await db.from('p1_rooms').select('*').order('created_at');if(r.error)throw r.error;rooms=r.data;room=rooms.find(r=>r.id===room?.id)||rooms[0]||null;await loadPupils()}
async function loadPupils(){pupils=[];if(!room)return;const r=await db.from('p1_pupils').select('id,room_id,number,name,active').eq('room_id',room.id).order('number');if(r.error)throw r.error;pupils=r.data;deck=[];chosen=null}
const roomSelect=()=>`<label>ชุดรายชื่อ / ห้องเรียน<select id="p1c-room">${rooms.map(r=>`<option value="${r.id}" ${room?.id===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label>`;
function bindRoom(fn){$('#p1c-room',panel)?.addEventListener('change',async e=>{try{room=rooms.find(r=>r.id===e.target.value);await loadPupils();await fn()}catch(e){status(e.message)}})}
async function manage(){await loadRooms();open('ห้องเรียนและชุดรายชื่อ',`${roomSelect()}<div class="p1c-actions"></div>${room?`<p>สถานะ: ${room.is_open?'เปิดให้นักเรียนเข้า':'ปิดรับเข้าเรียน'}</p><div class="p1c-roster">${pupils.map(p=>`<div><span>${th(p.number)}. ${esc(p.name)}</span><button data-edit="${p.id}">แก้ไข / ออกรหัสใหม่</button><button data-delete="${p.id}" aria-label="ลบ ${esc(p.name)}">ลบ</button></div>`).join('')}</div>`:'<p>เริ่มจากสร้างห้องหรือชุดรายชื่อ</p>'}`);bindRoom(manage);const a=$('.p1c-actions',panel);
 button('เพิ่มห้อง / ชุดรายชื่อ',async()=>{const name=prompt('ตั้งชื่อห้องหรือชุดรายชื่อ');if(!name?.trim())return;const r=await db.from('p1_rooms').insert({name:name.trim(),owner_id:session.user.id}).select().single();if(r.error)throw r.error;room=r.data;await manage()},a);
 if(!room)return;
 button('เปลี่ยนชื่อชุด',async()=>{const name=prompt('ชื่อใหม่',room.name);if(!name?.trim())return;const r=await db.from('p1_rooms').update({name:name.trim()}).eq('id',room.id);if(r.error)throw r.error;await manage()},a);
 button(room.is_open?'ปิดรับเข้าเรียน':'เปิดรับเข้าเรียน',async()=>{const r=await db.from('p1_rooms').update({is_open:!room.is_open}).eq('id',room.id);if(r.error)throw r.error;await manage()},a);
 button('ลิงก์ / QR ประจำห้อง',()=>share(new URL('index.html#room='+room.code,base).href,room.name),a);
 button('เพิ่มนักเรียน',()=>editPupil(),a);button('กำหนดบทที่เรียน',assignUnits,a);
 panel.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPupil(pupils.find(p=>p.id===b.dataset.edit)));
 panel.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('ลบนักเรียนคนนี้และยกเลิกสิทธิ์เข้าห้อง?'))return;const r=await db.from('p1_pupils').delete().eq('id',b.dataset.delete);if(r.error)status('ลบไม่ได้ หากมีผลการเรียนอยู่ให้เก็บรายชื่อนี้ไว้');else await manage()});
}
function assignUnits(){open('บทที่เปิดให้เรียน',`<form id="p1c-units">${Array.from({length:12},(_,i)=>`<label class="p1c-check"><input type="checkbox" value="${i+1}" ${room.units.includes(i+1)?'checked':''}>บทที่ ${th(i+1)}</label>`).join('')}<button>บันทึก</button></form>`);$('#p1c-units',panel).onsubmit=async e=>{e.preventDefault();try{const units=[...panel.querySelectorAll('input:checked')].map(x=>+x.value);const r=await db.from('p1_rooms').update({units}).eq('id',room.id);if(r.error)throw r.error;await manage()}catch(e){status(e.message)}}}
function token(){return [...crypto.getRandomValues(new Uint8Array(32))].map(n=>n.toString(16).padStart(2,'0')).join('')}
function editPupil(p){open(p?'แก้ไขและออกรหัสใหม่':'เพิ่มนักเรียน',`<form id="p1c-pupil"><label>เลขที่<input name="number" type="number" min="1" max="999" required value="${p?.number||pupils.length+1}"></label><label>ชื่อที่ใช้แสดง<input name="name" maxlength="120" required value="${esc(p?.name||'')}"></label><label>รหัสนักเรียน ๖–๑๒ หลัก<input name="pin" inputmode="numeric" pattern="[0-9]{6,12}" minlength="6" maxlength="12" required autocomplete="new-password"></label>${p?'<p>บันทึกแล้ว QR และการเข้าสู่ระบบเดิมของคนนี้จะถูกยกเลิก</p>':''}<button>บันทึกและสร้าง QR</button></form>`);$('#p1c-pupil',panel).onsubmit=async e=>{e.preventDefault();const btn=$('button',e.target);btn.disabled=true;try{const f=new FormData(e.target),secret=token();await rpc('save_pupil',{id:p?.id||null,room_id:room.id,number:+f.get('number'),name:f.get('name'),pin:f.get('pin'),token:secret});await share(new URL('index.html#student='+secret,base).href,f.get('name'))}catch(e){status(e.message);btn.disabled=false}}}
async function share(url,title){open('ลิงก์ / QR · '+title,'<p>แจกเฉพาะผู้เรียนหรือผู้ปกครองที่เกี่ยวข้อง</p><canvas id="p1c-qr"></canvas><label>ลิงก์<input id="p1c-link" readonly></label><div class="p1c-actions"></div>');$('#p1c-link',panel).value=url;const a=$('.p1c-actions',panel);button('คัดลอกลิงก์',async()=>{await navigator.clipboard.writeText(url);status('คัดลอกแล้ว')},a);try{const {default:QR}=await import('https://cdn.jsdelivr.net/npm/qrcode@1.5.4/+esm');await QR.toCanvas($('#p1c-qr',panel),url,{width:280,margin:2});button('ดาวน์โหลด QR',()=>{const a=document.createElement('a');a.href=$('#p1c-qr',panel).toDataURL();a.download='P1-QR.png';a.click()},$('.p1c-actions',panel))}catch{status('โหลด QR ไม่สำเร็จ สามารถคัดลอกลิงก์ได้')}}
async function joinLink(){const h=new URLSearchParams(location.hash.slice(1)),secret=h.get('student'),code=h.get('room');if(!secret&&!code)return;history.replaceState(null,'',location.pathname+location.search);await anonymous();await refresh();if(profile.role==='teacher'){home();status('กำลังใช้บัญชีครู หากต้องการเข้าฐานะนักเรียนให้ออกจากระบบก่อน แล้วเปิดลิงก์ใหม่');return}if(secret){await rpc('join',{token:secret});await refresh();home();return}const info=await rpc('room_info',{code});open('เข้าห้อง '+info.name,`<form id="p1c-join"><label>เลือกชื่อ<select name="pupil_id" required><option value="">เลือกชื่อของหนู</option>${info.pupils.map(p=>`<option value="${p.id}">${th(p.number)}. ${esc(p.name)}</option>`).join('')}</select></label><label>รหัสที่ครูให้<input name="pin" type="password" inputmode="numeric" required autocomplete="off"></label><button>เข้าเรียน</button></form>`);$('#p1c-join',panel).onsubmit=async e=>{e.preventDefault();const b=$('button',e.target);b.disabled=true;try{await rpc('join',{code,...Object.fromEntries(new FormData(e.target))});await refresh();home()}catch(e){status(e.message);b.disabled=false}}}
async function selectMode(){await loadRooms();open('ใช้เครื่องร่วมกัน',`${roomSelect()}<label>รูปแบบ<select id="p1c-mode"><option value="class">ฝึกพร้อมกันทั้งห้อง</option><option value="teacher_selected">ให้นักเรียนตอบรายคน</option></select></label><label>ผู้ตอบ<select id="p1c-answerer"><option value="">เลือกผู้ตอบ</option>${pupils.map(p=>`<option value="${p.id}">${th(p.number)}. ${esc(p.name)}</option>`).join('')}</select></label><div class="p1c-actions"></div>`);bindRoom(selectMode);$('#p1c-mode',panel).value=mode;button('เลือกใช้',()=>{if(!room)throw Error('กรุณาสร้างห้องก่อน');mode=$('#p1c-mode',panel).value;chosen=$('#p1c-answerer',panel).value||null;if(mode==='teacher_selected'&&!chosen)throw Error('กรุณาเลือกผู้ตอบ');sessionStorage.setItem('p1-class-selection',JSON.stringify({room_id:room.id,mode,pupil_id:chosen,pupil_name:pupils.find(p=>p.id===chosen)?.name||null}));document.dispatchEvent(new Event('p1-trace-context'));status('เลือกแล้ว ผลทั้งห้องจะไม่ถูกนับเป็นคะแนนของนักเรียนทุกคน')},$('.p1c-actions',panel))}
async function randomPanel(){await loadRooms();open('สุ่มชื่อ / เลขที่',`${roomSelect()}<label>สุ่มจาก<select id="p1c-source"><option value="names">รายชื่อในชุด</option><option value="numbers">ช่วงเลขที่</option></select></label><div class="p1c-range"><label>เริ่ม<input id="p1c-from" type="number" min="1" max="999" value="1"></label><label>ถึง<input id="p1c-to" type="number" min="1" max="999" value="${pupils.length||30}"></label></div><label>เลขที่ขาดเรียน / ยกเว้น (คั่นด้วยจุลภาค)<input id="p1c-exclude" placeholder="เช่น 3, 8"></label><label class="p1c-check"><input id="p1c-repeat" type="checkbox">สุ่มซ้ำได้</label><div class="p1c-random" aria-live="polite">พร้อมสุ่ม</div><div class="p1c-actions"></div>`);bindRoom(randomPanel);deck=[];lastRandom='';panel.querySelectorAll('input,select').forEach(e=>e.addEventListener('change',()=>{deck=[];lastRandom=''}));button('สุ่ม',()=>{const excluded=new Set($('#p1c-exclude',panel).value.split(/[,\s]+/).map(Number));const start=+$('#p1c-from',panel).value,end=+$('#p1c-to',panel).value;if(start<1||end>999||end<start)throw Error('ช่วงเลขที่ไม่ถูกต้อง');const choices=$('#p1c-source',panel).value==='names'?pupils.filter(p=>!excluded.has(p.number)).map(p=>`${th(p.number)}. ${p.name}`):Array.from({length:end-start+1},(_,i)=>start+i).filter(n=>!excluded.has(n)).map(th);if(!choices.length)throw Error('ไม่มีรายชื่อหรือเลขที่ให้สุ่ม');const repeat=$('#p1c-repeat',panel).checked;if(!repeat&&!deck.length&&lastRandom){status('ครบทุกคนแล้ว กดเริ่มรอบใหม่');return}if(!deck.length)deck=[...choices];const pool=repeat?choices:deck;const a=new Uint32Array(1);crypto.getRandomValues(a);const index=Math.floor(a[0]/4294967296*pool.length);lastRandom=repeat?pool[index]:pool.splice(index,1)[0];$('.p1c-random',panel).textContent=lastRandom;status(repeat?'':`เหลือ ${th(deck.length)} คน / หมายเลข`)},$('.p1c-actions',panel));button('เริ่มรอบใหม่',()=>{deck=[];lastRandom='';$('.p1c-random',panel).textContent='พร้อมสุ่ม';status('')},$('.p1c-actions',panel))}
async function results(){await loadRooms();let rows=[];if(room){const r=await db.from('p1_class_results').select('*').eq('room_id',room.id).order('created_at',{ascending:false}).limit(200);if(r.error)throw r.error;rows=r.data}open('ผลกิจกรรมล่าสุด',`${roomSelect()}<p>ผลรายบุคคลแยกจากการฝึกทั้งห้อง · แสดงล่าสุดไม่เกิน ๒๐๐ รายการ</p><div class="p1c-results">${rows.map(r=>`<p>${esc(r.mode==='class'?'ทั้งห้อง':pupils.find(p=>p.id===r.pupil_id)?.name||'ผู้เรียน')} · บท ${th(r.unit)} · ${esc(r.activity)} · ${th(r.correct)}/${th(r.total)}</p>`).join('')||'<p>ยังไม่มีผลกิจกรรม</p>'}</div>`);bindRoom(results)}
window.P1Classroom={async saveResult(result){await refresh();if(profile.role==='guest')throw Error('กรุณาเข้าห้องก่อนบันทึกผล');let context={mode:'individual'};if(profile.role==='teacher'){context=JSON.parse(sessionStorage.getItem('p1-class-selection')||'null');if(!context)throw Error('เลือกห้องและผู้ตอบก่อนบันทึกผล')}return rpc('result',{...result,...context,id:result.id||crypto.randomUUID()})},getProfile:()=>profile,getTraceContext:traceContext,async tracing(action,args={},expected){
 const before=traceContext();if(expected&&before.key!==expected)throw Error('ผู้ตอบเปลี่ยนแล้ว กรุณาตรวจใหม่');
 await refresh();const context=traceContext();if(!context.ready)throw Error('เข้าห้องเรียน หรือเลือกผู้ตอบก่อนบันทึก');
 if(context.key!==before.key)throw Error('ผู้ตอบเปลี่ยนแล้ว กรุณาตรวจใหม่');
 const r=await db.rpc('p1_tracing',{action,args:{...args,...context.args}});if(r.error)throw r.error;return r.data;
}};
function traceContext(){
 let choice=null;try{choice=JSON.parse(sessionStorage.getItem('p1-class-selection')||'null')}catch{}
 if(profile.role==='student')return {ready:true,key:'student:'+profile.pupil.id,label:profile.pupil.name,args:{mode:'individual'}};
 if(profile.role==='teacher'&&choice)return {ready:true,key:session.user.id+':'+JSON.stringify(choice),label:choice.mode==='class'?'ฝึกทั้งห้อง':choice.pupil_name||'ผู้เรียนที่ครูเลือก',args:choice};
 return {ready:false,key:'guest',label:profile.role==='teacher'?'ยังไม่ได้เลือกผู้ตอบ':'ฝึกโดยไม่เข้าห้องเรียน',args:{}};
}
async function traceResults(){
 await loadRooms();let rows=[];if(room){for(let start=0;;start+=500){const r=await db.from('p1_trace_attempts').select('*').eq('room_id',room.id).order('created_at',{ascending:true}).order('id').range(start,start+499);if(r.error)throw r.error;rows.push(...r.data);if(r.data.length<500)break}}
 const groups=new Map();for(const r of rows){const k=[r.pupil_id,r.mode,r.activity,r.symbol,r.algorithm].join('|');const prev=groups.get(k);if(prev){prev.best=Math.max(prev.best,r.score);prev.count++}else groups.set(k,{...r,first:r.score,best:r.score,count:1})}
 open('คะแนนฝึกเขียน',`${roomSelect()}<p>ความใกล้เคียงกับตัวอย่าง · ครั้งแรก / ดีที่สุด · ผลทั้งห้องแยกจากรายบุคคล</p><div class="p1c-results">${[...groups.values()].map(r=>`<p>${esc(r.mode==='class'?'ทั้งห้อง':pupils.find(p=>p.id===r.pupil_id)?.name||'ผู้เรียน')} · ${esc(r.activity)} · ${esc(r.symbol)} · ${r.algorithm==='trace-v2'?'เกณฑ์ใหม่':'เกณฑ์เดิม'} · ${th(r.first)}% / ${th(r.best)}% (${th(r.count)} ครั้ง)</p>`).join('')||'<p>ยังไม่มีคะแนนฝึกเขียน</p>'}</div>`);bindRoom(traceResults);
}

// Page-relative drawing: a separate overlay never changes reading tokens or audio.
const toolbar=document.createElement('div');toolbar.className='p1c-toolbar';toolbar.hidden=true;document.body.append(toolbar);
function pageKey(){return location.pathname+'?'+location.search+'#'+(sessionStorage.getItem('p1-full-page-'+(new URLSearchParams(location.search).get('unit')||1))||'0')}
function localKey(){return 'p1-drawing:'+session.user.id+':'+key}
function saveLocal(){try{sessionStorage.setItem(localKey(),JSON.stringify(strokes))}catch{}}
function remember(){undo.push(structuredClone(strokes));if(undo.length>40)undo.shift();redo=[]}
function eraseAt(p){strokes=strokes.filter(s=>!s.points.some((q,i)=>{const a=s.points[Math.max(0,i-1)],dx=q[0]-a[0],dy=q[1]-a[1],len=dx*dx+dy*dy,t=len?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/len)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy)<18}));paint();saveLocal()}
function paint(){if(!svg)return;svg.replaceChildren();for(const s of strokes){const p=document.createElementNS('http://www.w3.org/2000/svg','polyline');p.setAttribute('points',s.points.map(p=>p.join(',')).join(' '));p.setAttribute('fill','none');p.setAttribute('stroke',s.color);p.setAttribute('stroke-width',s.width);p.setAttribute('stroke-linecap','round');p.setAttribute('stroke-linejoin','round');p.setAttribute('opacity',s.alpha||1);svg.append(p)}svg.style.pointerEvents=drawMode?'auto':'none'}
function attachDrawing(){if(profile.role!=='teacher'||toolbar.hidden)return;const target=$('.native-source-layout')||$('.book-paper')||$('main');if(!target)return;const next=pageKey();if(host===target&&svg?.isConnected&&key===next)return;if(key)saveLocal();key=next;host=target;svg?.remove();if(getComputedStyle(host).position==='static')host.style.position='relative';svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('p1c-ink');svg.setAttribute('data-swipe-ignore','');host.append(svg);const r=host.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 1000 ${1000*r.height/r.width}`);strokes=JSON.parse(sessionStorage.getItem(localKey())||'[]');undo=[];redo=[];paint();let erasing=false;const point=e=>{const r=svg.getBoundingClientRect();return [(e.clientX-r.left)/r.width*1000,(e.clientY-r.top)/r.width*1000]};svg.onpointerdown=e=>{if(!drawMode)return;e.preventDefault();e.stopPropagation();svg.setPointerCapture(e.pointerId);const p=point(e);remember();if(drawMode==='eraser'){erasing=true;eraseAt(p);return}activeStroke={points:[p,[p[0]+.1,p[1]+.1]],color,width:drawMode==='highlight'?width*4:width,alpha:drawMode==='highlight'?.28:1};strokes.push(activeStroke);redo=[];paint()};svg.onpointermove=e=>{if(erasing){e.preventDefault();e.stopPropagation();eraseAt(point(e));return}if(!activeStroke)return;e.preventDefault();e.stopPropagation();activeStroke.points.push(point(e));paint()};svg.onpointerup=svg.onpointercancel=e=>{e.stopPropagation();erasing=false;activeStroke=null;saveLocal()};svg.addEventListener('click',e=>e.stopPropagation());}
function enableDrawing(){toolbar.hidden=false;toolbar.innerHTML='<strong>เครื่องมือเขียน</strong>';for(const [name,value] of [['ใช้งานหน้าเว็บ',''],['ปากกา','pen'],['ไฮไลต์','highlight'],['ยางลบ','eraser']])button(name,()=>{drawMode=value;paint();toolbar.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===value)))},toolbar).dataset.mode=value;
 const c=document.createElement('input');c.type='color';c.value=color;c.setAttribute('aria-label','สีปากกา');c.oninput=()=>color=c.value;toolbar.append(c);const w=document.createElement('input');w.type='range';w.min=2;w.max=14;w.value=width;w.setAttribute('aria-label','ความหนาปากกา');w.oninput=()=>width=+w.value;toolbar.append(w);
 button('ย้อนกลับ',()=>{if(undo.length){redo.push(structuredClone(strokes));strokes=undo.pop()}paint();saveLocal()},toolbar);button('ทำซ้ำ',()=>{if(redo.length){undo.push(structuredClone(strokes));strokes=redo.pop()}paint();saveLocal()},toolbar);button('ล้างหน้านี้',()=>{if(!confirm('ลบลายเขียนทั้งหมดในหน้านี้?'))return;remember();strokes=[];paint();saveLocal()},toolbar);
 button('บันทึกลายเขียน',async()=>{const r=await db.from('p1_annotations').upsert({owner_id:session.user.id,page_key:key,strokes,updated_at:new Date().toISOString()});if(r.error)alert('บันทึกไม่สำเร็จ: '+r.error.message);else alert('บันทึกลายเขียนแล้ว')},toolbar);
 button('โหลดที่บันทึก',async()=>{const r=await db.from('p1_annotations').select('strokes').eq('owner_id',session.user.id).eq('page_key',key).maybeSingle();if(r.error){alert(r.error.message);return}if(!r.data){alert('ยังไม่มีลายเขียนที่บันทึกในหน้านี้');return}if(strokes.length&&!confirm('แทนลายเขียนปัจจุบันด้วยที่บันทึกไว้?'))return;remember();strokes=r.data.strokes;paint();saveLocal()},toolbar);
 button('ปิดเครื่องมือ',()=>{drawMode='';paint();toolbar.hidden=true},toolbar);attachDrawing();}
let observer=new MutationObserver(()=>{installMenu();attachDrawing()});observer.observe(document.body,{childList:true,subtree:true});
// Auth callback work runs after the auth lock has been released.
db.auth.onAuthStateChange(()=>setTimeout(()=>refresh().catch(()=>{}),0));
try{await refresh();await joinLink()}catch(e){installMenu();open('การเชื่อมต่อห้องเรียน','<p>บทเรียนเดิมยังเปิดอ่านได้ตามปกติ</p>');status(e.message)}
