const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const dir=path.join(__dirname,'../literature'),book=JSON.parse(fs.readFileSync(path.join(dir,'book.json'),'utf8'));
test('eight workbook-verified pairs cover every source chapter page exactly once',()=>{assert.deepEqual(book.chapters.map(c=>[c.id,c.pairedUnit,c.workbook]),[[1,4,1],[2,5,1],[3,6,1],[4,7,2],[5,8,2],[6,9,2],[7,10,2],[8,11,2]]);const pages=book.chapters.flatMap(c=>c.pages);assert.deepEqual(pages.map(p=>p.pdfPage),Array.from({length:77},(_,i)=>i+8));for(const p of pages){assert.ok(fs.existsSync(path.join(dir,'assets',`page-${p.pdfPage}.webp`)));for(const l of p.lines)for(const word of l.words){assert.ok(!/[‘’•—]/.test(word.text),word.text);assert.ok(word.box.every(Number.isFinite));for(const c of word.chars)assert.ok(fs.existsSync(path.join(dir,'fonts',c[3]+'.otf')))}}});
test('critical Thai glyphs and connected words decoded for audio without segmentation',()=>{const all=book.chapters.flatMap(c=>c.pages).flatMap(p=>p.lines.flatMap(l=>l.words.map(w=>w.text)));for(const s of ['ฟัง','แบ่งปัน','กตัญญู','เอื้อเฟื้อ','เจ้าเนื้อละมุน','พระมหากษัตริย์'])assert.ok(all.includes(s),s);assert.ok(!all.includes('ฟ’ง'))});
async function boot(chapter=1,page=4){const d=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{url:`https://webbase-x.github.io/is/P1/literature/?chapter=${chapter}&page=${page}`,runScripts:'outside-only'}),w=d.window,utterances=[];w.fetch=async()=>({ok:true,json:async()=>book});w.scrollTo=()=>{};w.FontFace=class{async load(){return this}};w.document.fonts={add(){}};w.Image=class{async decode(){}};w.SpeechSynthesisUtterance=function(text){this.text=text};w.speechSynthesis={getVoices:()=>[],speak:u=>utterances.push(u),cancel(){}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(fs.readFileSync(path.join(dir,'../course-flow.js'),'utf8'));w.eval(fs.readFileSync(path.join(dir,'reader.js'),'utf8'));await new Promise(r=>setTimeout(r,20));return{d,w,doc:w.document,utterances}}
test('every chapter renders native word controls, source art and the correct paired link',async()=>{for(let n=1;n<=8;n++){const {d,doc}=await boot(n,3);assert.ok(doc.querySelectorAll('.word').length>5);assert.match(doc.querySelector('#paired').href,new RegExp('unit='+(n+3)+'&'));assert.equal(doc.querySelector('.source-page').style.visibility,'visible');assert.ok(doc.querySelector('image').getAttribute('href'));doc.querySelector('#viewMode').click();assert.ok(doc.querySelectorAll('.plain button').length>5);d.window.close()}});
test('whole connected word highlights once and obsolete queue stops on page change',async()=>{const {d,doc,utterances}=await boot();doc.querySelector('.word').dispatchEvent(new d.window.MouseEvent('click',{bubbles:true}));assert.equal(utterances[0].text,'เจ้าเนื้อละมุน');assert.equal(doc.querySelectorAll('.speaking').length,1);doc.querySelector('#next').click();utterances[0].onend();await new Promise(r=>setTimeout(r,160));assert.equal(utterances.length,1);assert.equal(doc.querySelectorAll('.speaking').length,0);d.window.close()});
test('home adds exactly eight paired links and keeps all original cards',()=>{const d=new JSDOM(fs.readFileSync(path.join(dir,'../index.html'),'utf8'));assert.equal(d.window.document.querySelectorAll('.unit-card').length,13);assert.equal(d.window.document.querySelectorAll('.literature-pair a').length,8);d.window.close()});

test('highlight rectangles do not overlap neighbouring words on any page',()=>{for(const ch of book.chapters)for(const pg of ch.pages){const ws=pg.lines.filter(l=>l.read).flatMap(l=>l.words);for(let i=0;i<ws.length;i++){const a=ws[i].highlightBox;for(const bword of ws.slice(i+1)){const b=bword.highlightBox;const x=Math.min(a[2],b[2])-Math.max(a[0],b[0]),y=Math.min(a[3],b[3])-Math.max(a[1],b[1]);assert.ok(x<=0||y<=0,`${pg.pdfPage} ${ws[i].text} / ${bword.text}`)}}}});

test('all chapter covers combine two source pages and skip the duplicate cover step',async()=>{for(let c=1;c<=8;c++){const {d,doc}=await boot(c,1);assert.equal(doc.querySelector('svg').getAttribute('viewBox'),'0 0 1052 739');assert.equal(doc.querySelectorAll('svg image').length,2);const pages=book.chapters[c-1].pages;assert.equal(doc.querySelectorAll('#pages button').length,pages.length-1);doc.querySelector('#next').click();assert.equal(doc.querySelectorAll('svg image').length,1);assert.equal(doc.querySelector('image').getAttribute('href'),`assets/page-${pages[2].pdfPage}.webp`);doc.querySelector('#prev').click();assert.equal(doc.querySelectorAll('svg image').length,2);await new Promise(r=>setTimeout(r,10));d.window.close()}});
