const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const dir=path.join(__dirname,'../00-prerequisite');
function boot(page=1){
 const d=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{url:`https://webbase-x.github.io/is/P1/00-prerequisite/?page=${page}`,runScripts:'outside-only'});
 const w=d.window,utterances=[];w.scrollTo=()=>{};w.SpeechSynthesisUtterance=function(text){this.text=text};w.speechSynthesis={cancel(){},getVoices:()=>[],speak:u=>utterances.push(u)};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.eval(fs.readFileSync(path.join(dir,'trace-score.js'),'utf8'));w.eval(fs.readFileSync(path.join(dir,'readiness.js'),'utf8'));return{d,w,doc:w.document,utterances};
}
test('all 44 source cards appear once and assets exist',()=>{const {d,doc}=boot(2);const found=[];for(let n=0;n<44;n++){assert.equal(doc.querySelectorAll('[data-letter]').length,1);for(const b of doc.querySelectorAll('[data-letter]')){found.push(b.dataset.letter);assert.ok(fs.existsSync(path.join(dir,b.querySelector('img').getAttribute('src'))))}doc.querySelector('#next').click()}assert.equal(found.length,44);assert.equal(new Set(found).size,44);d.window.close()});
test('reading highlights the spoken card and page changes cancel the old queue',async()=>{const {d,doc,utterances}=boot(2);doc.querySelector('#readPage').click();assert.equal(utterances.length,1);assert.equal(utterances[0].text,'กอ ไก่');assert.equal(doc.querySelectorAll('.speaking').length,1);doc.querySelector('#next').click();utterances[0].onend();await new Promise(r=>setTimeout(r,260));assert.equal(utterances.length,1);assert.equal(doc.querySelectorAll('.speaking').length,0);d.window.close()});
test('all workbook source pages reachable and tone signs plus compound vowels present',()=>{const {d,doc}=boot(46);const sources=new Set(),symbols=[];for(let n=0;n<12;n++){doc.querySelectorAll('[data-source]').forEach(b=>sources.add(b.dataset.source));doc.querySelectorAll('[data-sample]').forEach(b=>symbols.push(b.dataset.sample));doc.querySelector('#next').click()}assert.equal(sources.size,27);for(const n of sources)assert.ok(fs.existsSync(path.join(dir,`assets/workbook-${n}.webp`)));for(const s of ['่','้','๊','๋','เ-ีย','เ-ือ','-ัว','๑๐','ษ'])assert.ok(symbols.includes(s),s);d.window.close()});
test('ink stays with its selected character and survives undo/redo and page revisit',()=>{const {d,doc,w}=boot(46);const board=doc.querySelector('#writing');board.getBoundingClientRect=()=>({left:0,top:0,width:720,height:340});board.setPointerCapture=()=>{};const ev={clientX:55,clientY:80,pointerId:1,button:0,preventDefault(){},stopPropagation(){}};board.onpointerdown(ev);board.onpointermove({...ev,clientY:120});board.onpointerup();assert.equal(doc.querySelectorAll('#ink polyline').length,1);doc.querySelector('#undoInk').click();assert.equal(doc.querySelectorAll('#ink polyline').length,0);doc.querySelector('#redoInk').click();assert.equal(doc.querySelectorAll('#ink polyline').length,1);doc.querySelector('[data-sample="ก"]').click();assert.equal(doc.querySelectorAll('#ink polyline').length,0);doc.querySelector('[data-sample="เส้น"]').click();assert.equal(doc.querySelectorAll('#ink polyline').length,1);doc.querySelector('#next').click();doc.querySelector('#previous').click();assert.equal(doc.querySelectorAll('#ink polyline').length,1);assert.ok(doc.querySelector('#writing').hasAttribute('data-swipe-ignore'));d.window.close()});
test('table of contents gives readiness its own card before unit one',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const d=new JSDOM(html);const cards=d.window.document.querySelectorAll('.unit-card');assert.equal(cards.length,13);assert.ok(cards[0].classList.contains('readiness-card'));assert.equal(cards[0].querySelector('h3').textContent,'เตรียมความพร้อม');assert.match(cards[1].querySelector('.unit-cover').href,/unit=1/);d.window.close()});
test('swiping across a card moves one consonant and does not trigger its audio',()=>{const {d,doc,w,utterances}=boot(2);const paper=doc.querySelector('#paper'),card=doc.querySelector('[data-letter]');const event=(type,x,y)=>new w.MouseEvent(type,{bubbles:true,clientX:x,clientY:y});card.dispatchEvent(event('pointerdown',250,150));card.dispatchEvent(event('pointerup',80,155));assert.equal(doc.querySelector('[data-letter]').dataset.letter,'1');doc.querySelector('[data-letter]').click();assert.equal(utterances.length,0);paper.dispatchEvent(event('pointerdown',100,100));paper.dispatchEvent(event('pointerup',105,250));assert.equal(doc.querySelector('[data-letter]').dataset.letter,'1');paper.dispatchEvent(event('pointerdown',80,150));paper.dispatchEvent(event('pointerup',250,150));assert.equal(doc.querySelector('[data-letter]').dataset.letter,'0');d.window.close()});

test('switching student context clears the previous learner ink and scores',async()=>{const {d,w,doc}=boot(46);let context={ready:true,key:'student:a',label:'A'};w.P1Classroom={getTraceContext:()=>context,tracing:async()=>[{activity:'เตรียมความพร้อม / แบบฝึกชุดที่ ๑ · ลากเส้นขึ้น–ลง',symbol:'ก',first:60,best:85,latest:85,attempts:2}]};doc.dispatchEvent(new w.Event('p1-trace-context'));await new Promise(r=>setTimeout(r,0));doc.querySelector('[data-sample="ก"]').click();assert.match(doc.querySelector('#traceSummary').textContent,/60%.*85%/);const board=doc.querySelector('#writing');board.getBoundingClientRect=()=>({left:0,top:0,width:720,height:340});const e={clientX:300,clientY:100,pointerId:1,button:0,preventDefault(){},stopPropagation(){}};board.onpointerdown(e);board.onpointerup();assert.equal(doc.querySelectorAll('#ink polyline').length,1);context={ready:true,key:'student:b',label:'B'};w.P1Classroom.tracing=async()=>[];doc.dispatchEvent(new w.Event('p1-trace-context'));await new Promise(r=>setTimeout(r,0));assert.equal(doc.querySelectorAll('#ink polyline').length,0);assert.doesNotMatch(doc.querySelector('#traceSummary').textContent,/60%|85%/);assert.match(doc.querySelector('#traceOwner').textContent,/B/);d.window.close()});
