const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const dir=path.join(__dirname,'../00-prerequisite');
function boot(page=1){
 const d=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{url:`https://webbase-x.github.io/is/P1/00-prerequisite/?page=${page}`,runScripts:'outside-only'});
 const w=d.window,utterances=[];w.scrollTo=()=>{};w.SpeechSynthesisUtterance=function(text){this.text=text};w.speechSynthesis={cancel(){},getVoices:()=>[],speak:u=>utterances.push(u)};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.eval(fs.readFileSync(path.join(dir,'readiness.js'),'utf8'));return{d,w,doc:w.document,utterances};
}
test('all 44 source cards appear once and assets exist',()=>{const {d,doc}=boot(2);const found=[];for(let n=0;n<8;n++){for(const b of doc.querySelectorAll('[data-letter]')){found.push(b.dataset.letter);assert.ok(fs.existsSync(path.join(dir,b.querySelector('img').getAttribute('src'))))}doc.querySelector('#next').click()}assert.equal(found.length,44);assert.equal(new Set(found).size,44);d.window.close()});
test('reading highlights the spoken card and page changes cancel the old queue',async()=>{const {d,doc,utterances}=boot(2);doc.querySelector('#readPage').click();assert.equal(utterances.length,1);assert.equal(utterances[0].text,'กอ ไก่');assert.equal(doc.querySelectorAll('.speaking').length,1);doc.querySelector('#next').click();utterances[0].onend();await new Promise(r=>setTimeout(r,260));assert.equal(utterances.length,1);assert.equal(doc.querySelectorAll('.speaking').length,0);d.window.close()});
test('all workbook source pages reachable and tone signs plus compound vowels present',()=>{const {d,doc}=boot(10);const sources=new Set(),symbols=[];for(let n=0;n<12;n++){doc.querySelectorAll('[data-source]').forEach(b=>sources.add(b.dataset.source));doc.querySelectorAll('[data-sample]').forEach(b=>symbols.push(b.dataset.sample));doc.querySelector('#next').click()}assert.equal(sources.size,27);for(const n of sources)assert.ok(fs.existsSync(path.join(dir,`assets/workbook-${n}.webp`)));for(const s of ['่','้','๊','๋','เ-ีย','เ-ือ','-ัว','๑๐','ษ'])assert.ok(symbols.includes(s),s);d.window.close()});
test('ink stays with its selected character and survives undo/redo and page revisit',()=>{const {d,doc,w}=boot(10);const board=doc.querySelector('#writing');board.getBoundingClientRect=()=>({left:0,top:0,width:720,height:340});board.setPointerCapture=()=>{};const ev={clientX:55,clientY:80,pointerId:1,button:0,preventDefault(){},stopPropagation(){}};board.onpointerdown(ev);board.onpointermove({...ev,clientY:120});board.onpointerup();assert.equal(doc.querySelectorAll('#ink polyline').length,1);doc.querySelector('#undoInk').click();assert.equal(doc.querySelectorAll('#ink polyline').length,0);doc.querySelector('#redoInk').click();assert.equal(doc.querySelectorAll('#ink polyline').length,1);doc.querySelector('[data-sample="ก"]').click();assert.equal(doc.querySelectorAll('#ink polyline').length,0);doc.querySelector('[data-sample="เส้น"]').click();assert.equal(doc.querySelectorAll('#ink polyline').length,1);doc.querySelector('#next').click();doc.querySelector('#previous').click();assert.equal(doc.querySelectorAll('#ink polyline').length,1);assert.ok(doc.querySelector('#writing').hasAttribute('data-swipe-ignore'));d.window.close()});
test('table of contents gives readiness its own card before unit one',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const d=new JSDOM(html);const cards=d.window.document.querySelectorAll('.unit-card');assert.equal(cards.length,13);assert.ok(cards[0].classList.contains('readiness-card'));assert.equal(cards[0].querySelector('h3').textContent,'เตรียมความพร้อม');assert.match(cards[1].querySelector('.unit-cover').href,/unit=1/);d.window.close()});
